//! What roux build writes from contracts: the app's module for each
//! template (its contract and a typed `render!`), and for the templates
//! object, the throwaway platform glue lays the contracts out from and the
//! registry render.zig compiles.
//!
//! Roc source uses tabs, which Zig's multiline strings cannot hold: they
//! are written as `\t`.

const std = @import("std");
const assert = std.debug.assert;
const Writer = std.Io.Writer;
const contract_ = @import("contract.zig");
const Contract = contract_.Contract;

/// A record or list type longer than this (with its indentation) is
/// written one field per line.
const line_columns_max = 72;

pub const Module = struct {
    /// `Page` for `Page.rocstache`.
    name: []const u8,
    contract: *const Contract,
    /// The contract as one line (contract.write_line), and its hash.
    line: []const u8,
    id: u64,

    /// A template that reads nothing (`Bottom`, a closing partial): glue
    /// cannot lay out `{}` (a hosted function drops a zero-sized
    /// argument), so its box holds a `U8` placeholder instead.
    pub fn empty(module: Module) bool {
        return std.mem.eql(u8, module.line, "{}");
    }
};

/// The app's `Page.roc`.
pub fn write_module(module: Module, writer: *Writer) Writer.Error!void {
    try writer.print(
        "# Generated by roux build from {0s}.rocstache. DO NOT EDIT.\n" ++
            "# The template's contract only: markup changes leave this file alone.\n" ++
            "import pf.Rocstache\n\n{0s} :: [].{{\n\n",
        .{module.name},
    );
    if (module.contract.docs.len > 0) {
        var lines = std.mem.splitScalar(u8, module.contract.docs, '\n');
        while (lines.next()) |line| try writer.print("\t{s}\n", .{std.mem.trim(u8, line, " \t")});
    } else {
        const inferred = "\t## What `{s}.rocstache` reads, inferred from its tags.\n";
        try writer.print(inferred, .{module.name});
    }
    try writer.writeAll("\tCtx : ");
    try write_type(module.contract, module.contract.root, 1, writer);
    try writer.print(
        "\n\n\t## The page: the template as compiled into the app, rendered by the host.\n" ++
            "\trender! : Ctx => Str\n" ++
            "\trender! = |{s}| Rocstache.compiled_render!(0x{x:0>16}, Box.box({s}))\n}}\n",
        if (module.empty()) .{ "_ctx", module.id, "0.U8" } else .{ "ctx", module.id, "ctx" },
    );
}

/// A type as `roc fmt` lays it out: on one line when it fits, else a
/// record one field per line, with a trailing comma.
fn write_type(
    contract: *const Contract,
    index: u16,
    indent: u8,
    writer: *Writer,
) Writer.Error!void {
    assert(indent < 64);
    var line_buffer: [line_columns_max]u8 = undefined;
    var line: Writer = .fixed(&line_buffer);
    const fits = if (contract_.write_line(contract, index, &line)) |_|
        @as(usize, indent) * 4 + line.buffered().len <= line_columns_max
    else |_|
        false;
    if (fits) return writer.writeAll(line.buffered());
    const type_ = contract.get(index);
    switch (type_.kind) {
        .list => {
            try writer.writeAll("List(\n");
            try write_tabs(indent + 1, writer);
            try write_type(contract, type_.element, indent + 1, writer);
            try writer.writeAll(",\n");
            try write_tabs(indent, writer);
            try writer.writeAll(")");
        },
        .record => {
            var buffer: [contract_.fields_max]contract_.Field = undefined;
            try writer.writeAll("{\n");
            for (contract.sorted_fields(index, &buffer)) |f| {
                try write_tabs(indent + 1, writer);
                try writer.print("{s} : ", .{f.name});
                try write_type(contract, f.type, indent + 1, writer);
                try writer.writeAll(",\n");
            }
            try write_tabs(indent, writer);
            try writer.writeAll("}");
        },
        .unknown, .str, .int, .bool, .other => unreachable,
    }
}

fn write_tabs(count: u8, writer: *Writer) Writer.Error!void {
    for (0..count) |_| try writer.writeAll("\t");
}

/// The hosted function's name for a template: `contract_indexpage`.
pub fn hosted_name(name: []const u8, buffer: []u8) []const u8 {
    assert(buffer.len >= name.len);
    return std.ascii.lowerString(buffer[0..name.len], name);
}

/// `Contracts.roc`: one hosted function per contract, taking it concretely,
/// so glue emits each as an `extern struct` in Roc's layout.
pub fn write_contracts(modules: []const Module, writer: *Writer) Writer.Error!void {
    try writer.writeAll("Contracts := [].{\n");
    for (modules) |module| {
        if (module.empty()) continue;
        var buffer: [256]u8 = undefined;
        const lower = hosted_name(module.name, &buffer);
        try writer.print("\t{s}! : {s} => {{}}\n", .{ lower, module.line });
    }
    try writer.writeAll("}\n");
}

/// The throwaway platform's `main.roc`.
pub fn write_platform(modules: []const Module, writer: *Writer) Writer.Error!void {
    try writer.writeAll("platform \"contracts\"\n" ++
        "\trequires {} { main! : () => {} }\n" ++
        "\texposes []\n\tpackages {}\n" ++
        "\tprovides { \"contracts_main\": main_for_host! }\n" ++
        "\thosted {\n");
    for (modules) |module| {
        if (module.empty()) continue;
        var buffer: [256]u8 = undefined;
        const lower = hosted_name(module.name, &buffer);
        try writer.print("\t\t\"contract_{s}\": Contracts.{s}!,\n", .{ lower, lower });
    }
    try writer.writeAll("\t}\n" ++
        "\ttargets: { inputs_dir: \"targets/\", x64musl: { inputs: [app] } }\n\n" ++
        "import Contracts\n\nmain_for_host! : () => {}\nmain_for_host! = || main!()\n");
}

/// `templates.zig`, the registry the templates object compiles.
pub fn write_registry(modules: []const Module, writer: *Writer) Writer.Error!void {
    try writer.writeAll(
        \\//! Generated by roux build. DO NOT EDIT. The app's templates, each
        \\//! with its id and its contract's Zig type, as glue laid it out.
        \\pub const abi = @import("glue/roc_platform_abi.zig");
        \\
        \\fn Arg(comptime f: anytype) type {
        \\    return @typeInfo(@TypeOf(f)).@"fn".param_types[0].?;
        \\}
        \\
        \\/// A template that reads nothing: its box holds a `U8` placeholder.
        \\pub const Empty = extern struct { placeholder: u8 };
        \\
        \\pub const all = .{
        \\
    );
    for (modules) |module| {
        var buffer: [256]u8 = undefined;
        var ctx_buffer: [300]u8 = undefined;
        const lower = hosted_name(module.name, &buffer);
        const ctx = if (module.empty())
            "Empty"
        else
            std.fmt.bufPrint(&ctx_buffer, "Arg(abi.contract_{s})", .{lower}) catch unreachable;
        try writer.print(
            "    .{{ .name = \"{s}\", .id = 0x{x:0>16}, .Ctx = {s}, " ++
                ".source = @embedFile(\"{s}.rocstache\") }},\n",
            .{ module.name, module.id, ctx, module.name },
        );
    }
    try writer.writeAll("};\n");
}

const testing = std.testing;
const parse = @import("parse.zig");

test "roc: a module, short and long contracts" {
    const source = "{{ title }}{{#rows}}{{ competitor }}{{ share }}{{ low }}{{ high }}" ++
        "{{ reach }}{{ value }}{{ tip }}{{/rows}}";
    var tree: parse.Tree = .{};
    var d: parse.Diagnostic = .{};
    try parse.parse(source, &tree, &d);
    const contract = try testing.allocator.create(Contract);
    defer testing.allocator.destroy(contract);
    var diagnostic: contract_.Diagnostic = .{};
    const templates = [_]contract_.Template{.{ .name = "Strip", .source = source, .tree = &tree }};
    try contract_.of(contract, &templates, &diagnostic);
    var line_buffer: [1024]u8 = undefined;
    var line: Writer = .fixed(&line_buffer);
    try contract_.write_line(contract, contract.root, &line);
    var buffer: [2048]u8 = undefined;
    var writer: Writer = .fixed(&buffer);
    const module: Module = .{
        .name = "Strip",
        .contract = contract,
        .line = line.buffered(),
        .id = contract_.id("Strip", line.buffered()),
    };
    try write_module(module, &writer);
    const hex = id_hex(module.id);
    const written = try std.mem.replaceOwned(u8, testing.allocator, writer.buffered(), &hex, "{x}");
    defer testing.allocator.free(written);
    try testing.expectEqualStrings(
        "# Generated by roux build from Strip.rocstache. DO NOT EDIT.\n" ++
            "# The template's contract only: markup changes leave this file alone.\n" ++
            "import pf.Rocstache\n\nStrip :: [].{\n\n" ++
            "\t## What `Strip.rocstache` reads, inferred from its tags.\n" ++
            "\tCtx : {\n" ++
            "\t\trows : List(\n\t\t\t{\n" ++
            "\t\t\t\tcompetitor : Str,\n\t\t\t\thigh : Str,\n\t\t\t\tlow : Str,\n" ++
            "\t\t\t\treach : Str,\n\t\t\t\tshare : Str,\n" ++
            "\t\t\t\ttip : Str,\n\t\t\t\tvalue : Str,\n" ++
            "\t\t\t},\n\t\t),\n" ++
            "\t\ttitle : Str,\n" ++
            "\t}\n\n" ++
            "\t## The page: the template as compiled into the app, rendered by the host.\n" ++
            "\trender! : Ctx => Str\n" ++
            "\trender! = |ctx| Rocstache.compiled_render!(0x" ++ "{x}" ++ ", Box.box(ctx))\n}\n",
        written,
    );
}

fn id_hex(value: u64) [16]u8 {
    var result: [16]u8 = undefined;
    _ = std.fmt.bufPrint(&result, "{x:0>16}", .{value}) catch unreachable;
    return result;
}
