//! The app's module for each template (`Menu.roc`): its contract (`Ctx`)
//! and `template`, one line, which makes the template's value: its tag of
//! the app's `Templates.Template`, which `Templates.roc` (also written here)
//! spells out. Written from the contracts alone, so a markup edit leaves
//! the modules as they are.
//!
//! Roc source uses tabs, which Zig's multiline strings cannot hold: they
//! are written as `\t`.

const std = @import("std");
const assert = std.debug.assert;
const Writer = std.Io.Writer;
const Allocator = std.mem.Allocator;
const contract_ = @import("contract.zig");
const Contract = contract_.Contract;

/// A record or list type longer than this (with its indentation) is
/// written one field per line.
const line_columns_max = 72;

pub const Module = struct {
    /// `Menu` for `Menu.rocstache`.
    name: []const u8,
    contract: *const Contract,
};

pub const Error = Writer.Error || Allocator.Error;

/// The app's `Menu.roc`.
pub fn write_module(module: Module, writer: *Writer) Error!void {
    try writer.print(
        "# Generated by roux build from {0s}.rocstache. DO NOT EDIT.\n" ++
            "# Its contract only: markup changes leave this file alone.\n" ++
            "import pf.Rocstache\n" ++
            "import Templates\n",
        .{module.name},
    );
    // The partials it calls, whose contracts its own names (`Top.Ctx`).
    const contract = module.contract;
    for (contract.types[0..contract.types_len], 0..) |type_, index| {
        if (type_.alias.len == 0) continue;
        const first = for (contract.types[0..index]) |earlier| {
            if (std.mem.eql(u8, earlier.alias, type_.alias)) break false;
        } else true;
        if (first) try writer.print("import {s}\n", .{type_.alias});
    }
    try writer.print("\n{s} :: [].{{\n\n", .{module.name});
    if (module.contract.docs.len > 0) {
        var lines = std.mem.splitScalar(u8, module.contract.docs, '\n');
        while (lines.next()) |line| try writer.print("\t{s}\n", .{std.mem.trim(u8, line, " \t")});
    } else {
        const inferred = "\t## What `{s}.rocstache` reads, inferred from its tags.\n";
        try writer.print(inferred, .{module.name});
    }
    try writer.writeAll("\tCtx : ");
    try write_type(module.contract, module.contract.root, 1, writer);
    try writer.print(
        "\n\n\t## The template's value: what a response sends, rendered by the\n" ++
            "\t## host from the template's bytecode as it is sent.\n" ++
            "\ttemplate : Ctx -> Rocstache.Template(Templates.Template)\n" ++
            "\ttemplate = |ctx| {{ layouts: Templates.layouts, template: {s}(ctx) }}\n}}\n",
        .{module.name},
    );
}

pub const Union = struct {
    /// The templates' names, sorted, and their contracts.
    names: []const []const u8,
    contracts: []const *const Contract,
    /// The layouts' identity (generate.zig), which the program carries.
    layouts: u64,
};

/// The app's `Templates.roc`: the union of its templates, a tag each, its
/// payload the template's contract spelled out (a template's module
/// imports this one, so it cannot import them), and the layouts' identity.
/// Every constructor's annotation names the whole union, so Roc lays out
/// the one glue laid out, whichever templates the app sends.
pub fn write_templates(templates: Union, writer: *Writer) Error!void {
    assert(templates.names.len == templates.contracts.len);
    try writer.writeAll("# Generated by roux build from the app's templates. DO NOT EDIT.\n" ++
        "# The contracts spelled out, so each template's module can import this one.\n" ++
        "\nTemplates :: [].{\n" ++
        "\t## Every template of the app, a tag each, holding what it reads.\n" ++
        "\tTemplate : [\n");
    for (templates.names, templates.contracts) |name, contract| {
        try writer.print("\t\t{s}(", .{name});
        try contract_.write_line(contract, contract.root, writer);
        try writer.writeAll("),\n");
    }
    try writer.print("\t]\n\n" ++
        "\t## The layouts these templates were compiled for: the host renders\n" ++
        "\t## only a value made for its program's.\n" ++
        "\tlayouts : U64\n" ++
        "\tlayouts = 0x{x:0>16}\n}}\n", .{templates.layouts});
}

/// A type as `roc fmt` lays it out: on one line when it fits, else a
/// record one field per line, with a trailing comma.
fn write_type(
    contract: *const Contract,
    index: u16,
    indent: u8,
    writer: *Writer,
) Writer.Error!void {
    assert(indent < 64);
    var line_buffer: [line_columns_max]u8 = undefined;
    var line: Writer = .fixed(&line_buffer);
    const fits = if (contract_.write_line_as(contract, index, &line, .named)) |_|
        @as(usize, indent) * 4 + line.buffered().len <= line_columns_max
    else |_|
        false;
    if (fits) return writer.writeAll(line.buffered());
    const type_ = contract.get(index);
    if (index != contract.root and type_.alias.len > 0) {
        return writer.print("{s}.Ctx", .{type_.alias});
    }
    switch (type_.kind) {
        .list => {
            try writer.writeAll("List(\n");
            try write_tabs(indent + 1, writer);
            try write_type(contract, type_.element, indent + 1, writer);
            try writer.writeAll(",\n");
            try write_tabs(indent, writer);
            try writer.writeAll(")");
        },
        .record => {
            try writer.writeAll("{\n");
            var fields = contract.fields_of(index);
            while (fields.next()) |f| {
                try write_tabs(indent + 1, writer);
                try writer.print("{s} : ", .{f.name});
                try write_type(contract, f.type, indent + 1, writer);
                try writer.writeAll(",\n");
            }
            try write_tabs(indent, writer);
            try writer.writeAll("}");
        },
        .unknown, .str, .int, .bool, .other => unreachable,
    }
}

fn write_tabs(count: u8, writer: *Writer) Writer.Error!void {
    for (0..count) |_| try writer.writeAll("\t");
}
