//! The app's module for each template (`Page.roc`): its contract (`Ctx`)
//! and `render!`, one line, which boxes the record and calls the host's
//! renderer with the template's index. Written from the contract alone, so
//! a markup edit leaves the module as it is.
//!
//! Roc source uses tabs, which Zig's multiline strings cannot hold: they
//! are written as `\t`.

const std = @import("std");
const assert = std.debug.assert;
const Writer = std.Io.Writer;
const Allocator = std.mem.Allocator;
const contract_ = @import("contract.zig");
const Contract = contract_.Contract;

/// A record or list type longer than this (with its indentation) is
/// written one field per line.
const line_columns_max = 72;

pub const Module = struct {
    /// `Page` for `Page.rocstache`.
    name: []const u8,
    contract: *const Contract,
    /// The template's index among the app's, sorted by name: where the
    /// code's header has its range.
    index: u32,
};

pub const Error = Writer.Error || Allocator.Error;

/// The app's `Page.roc`.
pub fn write_module(module: Module, writer: *Writer) Error!void {
    try writer.print(
        "# Generated by roux build from {0s}.rocstache. DO NOT EDIT.\n" ++
            "# Its contract only: markup changes leave this file alone.\n" ++
            "import pf.Rocstache\n",
        .{module.name},
    );
    // The partials it calls, whose contracts its own names (`Top.Ctx`).
    const contract = module.contract;
    for (contract.types[0..contract.types_len], 0..) |type_, index| {
        if (type_.alias.len == 0) continue;
        const first = for (contract.types[0..index]) |earlier| {
            if (std.mem.eql(u8, earlier.alias, type_.alias)) break false;
        } else true;
        if (first) try writer.print("import {s}\n", .{type_.alias});
    }
    try writer.print("\n{s} :: [].{{\n\n", .{module.name});
    if (module.contract.docs.len > 0) {
        var lines = std.mem.splitScalar(u8, module.contract.docs, '\n');
        while (lines.next()) |line| try writer.print("\t{s}\n", .{std.mem.trim(u8, line, " \t")});
    } else {
        const inferred = "\t## What `{s}.rocstache` reads, inferred from its tags.\n";
        try writer.print(inferred, .{module.name});
    }
    try writer.writeAll("\tCtx : ");
    try write_type(module.contract, module.contract.root, 1, writer);
    try writer.print(
        "\n\n\t## The page, rendered by the host from the template's bytecode.\n" ++
            "\trender! : Ctx => Rocstache.Html\n" ++
            "\trender! = |ctx| Rocstache.render!({d}, Box.box(ctx))\n}}\n",
        .{module.index},
    );
}

/// A type as `roc fmt` lays it out: on one line when it fits, else a
/// record one field per line, with a trailing comma.
fn write_type(
    contract: *const Contract,
    index: u16,
    indent: u8,
    writer: *Writer,
) Writer.Error!void {
    assert(indent < 64);
    var line_buffer: [line_columns_max]u8 = undefined;
    var line: Writer = .fixed(&line_buffer);
    const fits = if (contract_.write_line_as(contract, index, &line, .named)) |_|
        @as(usize, indent) * 4 + line.buffered().len <= line_columns_max
    else |_|
        false;
    if (fits) return writer.writeAll(line.buffered());
    const type_ = contract.get(index);
    if (index != contract.root and type_.alias.len > 0) {
        return writer.print("{s}.Ctx", .{type_.alias});
    }
    switch (type_.kind) {
        .list => {
            try writer.writeAll("List(\n");
            try write_tabs(indent + 1, writer);
            try write_type(contract, type_.element, indent + 1, writer);
            try writer.writeAll(",\n");
            try write_tabs(indent, writer);
            try writer.writeAll(")");
        },
        .record => {
            var buffer: [contract_.fields_max]contract_.Field = undefined;
            try writer.writeAll("{\n");
            for (contract.sorted_fields(index, &buffer)) |f| {
                try write_tabs(indent + 1, writer);
                try writer.print("{s} : ", .{f.name});
                try write_type(contract, f.type, indent + 1, writer);
                try writer.writeAll(",\n");
            }
            try write_tabs(indent, writer);
            try writer.writeAll("}");
        },
        .unknown, .str, .int, .bool, .other => unreachable,
    }
}

fn write_tabs(count: u8, writer: *Writer) Writer.Error!void {
    for (0..count) |_| try writer.writeAll("\t");
}
