//! The generated Roc: a module per query file, and `Database.roc`, the
//! schema and every statement in the order the host prepares them. Each
//! generated function names the SQL line it runs (`# Dishes.sql:6`), as
//! rocstache-gen names template lines. Pure: compiled statements in, text
//! out, tabs as Roc writes them.

const std = @import("std");
const assert = std.debug.assert;
const Writer = std.Io.Writer;
const types = @import("sqlite").types;
const compile = @import("compile.zig");
const names = @import("names.zig");
const position = @import("diagnostics.zig").position;

const Statement = compile.Statement;
const Field = compile.Field;
const Input = compile.Input;

/// A query file's module. `first_index` is its first statement's number in
/// `Database.roc`'s list.
pub fn write_module(
    w: *Writer,
    input: Input,
    statements: []const Statement,
    first_index: u32,
) Writer.Error!void {
    const module = input.name[0 .. input.name.len - ".sql".len];
    assert(names.is_pascal(module));
    try w.print("# Generated by roux-db from {s}. DO NOT EDIT.\n", .{input.name});
    try w.writeAll("import pf.Sqlite\n\n");
    try w.print("## The queries of `{s}`, typed by SQLite against `schema.sql`. Each runs a\n", .{
        input.name,
    });
    try w.writeAll("## statement the host prepared at startup (`Database.roc`).\n");
    try w.print("{s} :: [].{{\n", .{module});
    for (statements, first_index..) |statement, index| {
        try w.writeAll("\n");
        try write_query(w, module, input, statement, @intCast(index));
    }
    try w.writeAll("}\n");
}

fn write_query(
    w: *Writer,
    module: []const u8,
    input: Input,
    statement: Statement,
    index: u32,
) Writer.Error!void {
    var row_buffer: [names.name_bytes_max]u8 = undefined;
    const row = names.pascal_from_snake(statement.name, &row_buffer);
    const name_line = position(input.text, statement.name_offset).line;
    const sql_line = position(input.text, statement.sql_offset).line;
    if (statement.kind != .exec) {
        try w.print("\t## A row of `{s}`.\n\t{s} : ", .{ statement.name, row });
        try write_record_type(w, statement.columns);
        try w.writeAll("\n\n");
    }
    try w.print("\t## `{s}`, {s}:{d}: {s}.\n", .{
        statement.name, input.name, name_line,
        switch (statement.kind) {
            .one => "one row, or `NotFound`",
            .many => "the rows, at most `:many`'s bound (more is `TooManyRows`)",
            .exec => "no rows",
        },
    });
    try write_signature(w, statement, row);
    try w.print("\t{s}! = |db{s}| {{\n", .{
        statement.name, if (statement.params.len > 0) ", params" else "",
    });
    try w.print("\t\t{s} = Sqlite.{s}(db, {d}, ", .{
        if (statement.kind == .exec) "_" else "rows",
        if (statement.writes) "run_write!" else "run_read!",
        index,
    });
    try write_params(w, statement.params);
    try w.print(")? # {s}:{d}\n", .{ input.name, sql_line });
    try write_result(w, module, statement);
    try w.writeAll("\t}\n");
}

fn write_signature(w: *Writer, statement: Statement, row: []const u8) Writer.Error!void {
    try w.print("\t{s}! : Sqlite.{s}", .{
        statement.name, if (statement.writes) "Write" else "Read",
    });
    if (statement.params.len > 0) {
        try w.writeAll(", ");
        try write_record_type(w, statement.params);
    }
    switch (statement.kind) {
        .one => try w.print(" => Try({s}, [NotFound, DbErr(Sqlite.Err)])\n", .{row}),
        .many => try w.print(" => Try(List({s}), [DbErr(Sqlite.Err)])\n", .{row}),
        .exec => try w.writeAll(" => Try({}, [DbErr(Sqlite.Err)])\n"),
    }
}

/// `{ id : I64, due : Sqlite.Nullable(I64) }`
fn write_record_type(w: *Writer, fields: []const Field) Writer.Error!void {
    assert(fields.len > 0);
    try w.writeAll("{ ");
    for (fields, 0..) |field, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("{s} : ", .{field.name});
        try write_type(w, field.type);
    }
    try w.writeAll(" }");
}

fn write_type(w: *Writer, field_type: types.Type) Writer.Error!void {
    if (field_type.nullable) {
        try w.print("Sqlite.Nullable({s})", .{field_type.scalar.roc()});
    } else {
        try w.writeAll(field_type.scalar.roc());
    }
}

/// `[Sqlite.Param.i64(params.id), ...]`, in SQLite's parameter order.
fn write_params(w: *Writer, params: []const Field) Writer.Error!void {
    try w.writeAll("[");
    for (params, 0..) |param, i| {
        if (i > 0) try w.writeAll(", ");
        try w.writeAll("Sqlite.Param.");
        try write_helper(w, param.type);
        try w.print("(params.{s})", .{param.name});
    }
    try w.writeAll("]");
}

/// The suffix of a `Sqlite.Param` or `Sqlite.Cell` helper: `i64`,
/// `nullable_str`, ...
fn write_helper(w: *Writer, field_type: types.Type) Writer.Error!void {
    if (field_type.nullable) try w.writeAll("nullable_");
    try w.writeAll(@tagName(field_type.scalar));
}

fn write_result(w: *Writer, module: []const u8, statement: Statement) Writer.Error!void {
    switch (statement.kind) {
        .exec => try w.writeAll("\t\tOk({})\n"),
        .one => {
            try w.writeAll("\t\tmatch rows {\n");
            try w.writeAll("\t\t\t[] => Err(NotFound)\n");
            try w.writeAll("\t\t\t[");
            try write_cells_pattern(w, statement.columns);
            try w.writeAll("] => Ok(");
            try write_row_record(w, statement.columns);
            try w.writeAll(")\n");
            try w.print("\t\t\t_ => crash \"roux-db: {s}.{s}: {s}\"\n", .{
                module, statement.name, "rows the host should have refused",
            });
            try w.writeAll("\t\t}\n");
        },
        .many => {
            // As `roc fmt` lays it out.
            try w.writeAll("\t\tOk(\n\t\t\trows.map(\n\t\t\t\t|row| match row {\n\t\t\t\t\t");
            try write_cells_pattern(w, statement.columns);
            try w.writeAll(" => ");
            try write_row_record(w, statement.columns);
            try w.print("\n\t\t\t\t\t_ => crash \"roux-db: {s}.{s}: {s}\"\n", .{
                module, statement.name, "a row the host should have refused",
            });
            try w.writeAll("\t\t\t\t},\n\t\t\t),\n\t\t)\n");
        },
    }
}

/// `[c0, c1, c2]`: the cells, by position (a column's own name could be
/// a name the function already binds).
fn write_cells_pattern(w: *Writer, columns: []const Field) Writer.Error!void {
    try w.writeAll("[");
    for (columns, 0..) |_, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("c{d}", .{i});
    }
    try w.writeAll("]");
}

/// `{ id: Sqlite.Cell.i64(c0), ... }`
fn write_row_record(w: *Writer, columns: []const Field) Writer.Error!void {
    try w.writeAll("{ ");
    for (columns, 0..) |column, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("{s}: Sqlite.Cell.", .{column.name});
        try write_helper(w, column.type);
        try w.print("(c{d})", .{i});
    }
    try w.writeAll(" }");
}

/// `Database.roc`: the schema and every statement, numbered as the query
/// modules call them.
pub fn write_database(
    w: *Writer,
    schema: Input,
    queries: []const Input,
    statements: []const Statement,
) Writer.Error!void {
    try w.writeAll("# Generated by roux-db from schema.sql");
    for (queries) |query| try w.print(", {s}", .{query.name});
    try w.writeAll(". DO NOT EDIT.\nimport pf.Sqlite\n\n");
    try w.writeAll("## The database: `schema.sql`, and every statement the queries beside it\n");
    try w.writeAll("## run, numbered as they call them. In `init!`:\n");
    try w.writeAll("## `Sqlite.open!(Database.at(path))`.\n");
    try w.writeAll("Database :: [].{\n");
    try w.writeAll("\tat : Str -> Sqlite.Database\n");
    try w.writeAll("\tat = |path| { path, schema, statements }\n}\n\n");
    try w.writeAll("schema : Str\nschema = ");
    try write_string(w, schema.text);
    try w.writeAll("\n\nstatements : List(Sqlite.Statement)\nstatements = [\n");
    for (statements, 0..) |statement, index| {
        try write_statement_entry(w, queries[statement.file - 1], statement, @intCast(index));
    }
    try w.writeAll("]\n");
}

fn write_statement_entry(
    w: *Writer,
    input: Input,
    statement: Statement,
    index: u32,
) Writer.Error!void {
    const module = input.name[0 .. input.name.len - ".sql".len];
    const line = position(input.text, statement.name_offset).line;
    try w.print("\t# {d}: {s}:{d}\n", .{ index, input.name, line });
    try w.print("\t{{ name: \"{s}.{s}\", sql: ", .{ module, statement.name });
    try write_string(w, statement.sql);
    try w.print(", writes: Bool.{s}, rows_max: {d}, params: ", .{
        if (statement.writes) "True" else "False", statement.rows_max,
    });
    try write_codes(w, statement.params);
    try w.writeAll(", columns: ");
    try write_codes(w, statement.columns);
    try w.writeAll(" },\n");
}

/// `[1, 19]`: the fields' type codes (sqlite/types.zig).
fn write_codes(w: *Writer, fields: []const Field) Writer.Error!void {
    try w.writeAll("[");
    for (fields, 0..) |field, i| {
        if (i > 0) try w.writeAll(", ");
        try w.print("{d}", .{field.type.code()});
    }
    try w.writeAll("]");
}

/// `bytes` as a Roc string literal, with quotes.
fn write_string(w: *Writer, bytes: []const u8) Writer.Error!void {
    try w.writeByte('"');
    var run_start: usize = 0;
    for (bytes, 0..) |byte, i| {
        const escape: ?[]const u8 = switch (byte) {
            '"' => "\\\"",
            '\\' => "\\\\",
            '$' => "\\$",
            '\n' => "\\n",
            '\t' => "\\t",
            '\r' => "\\r",
            else => null,
        };
        if (escape == null and byte >= 0x20 and byte != 0x7f) continue;
        try w.writeAll(bytes[run_start..i]);
        if (escape) |text| try w.writeAll(text) else try w.print("\\u({x})", .{byte});
        run_start = i + 1;
    }
    try w.writeAll(bytes[run_start..]);
    try w.writeByte('"');
}

test "emit: Roc string literals escape what Roc would read as syntax" {
    var buffer: [64]u8 = undefined;
    var w = Writer.fixed(&buffer);
    try write_string(&w, "a\"b\\c${d}\n\te\x01");
    try std.testing.expectEqualStrings("\"a\\\"b\\\\c\\${d}\\n\\te\\u(1)\"", w.buffered());
}
