//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must release owned refcounted arguments when done, using
//!   the release call named in each hosted symbol's doc comment below.
//! - Releasing a container releases its elements only when the container's own
//!   count reaches zero, which is what compiled Roc code does when it drops one
//!   it owns. Releasing the elements unconditionally double-frees them whenever
//!   the Roc caller still holds the container.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of Roc's fixed-point `Dec` value.
///
/// `num` stores the decimal value scaled by 10^18.
pub const RocDec = extern struct {
    num: i128,
};

comptime {
    if (@sizeOf(RocDec) != 16) @compileError("RocDec size mismatch");
    if (@alignOf(RocDec) != 16) @compileError("RocDec alignment mismatch");
}

pub const RocU8x16 = @Vector(16, u8);
pub const RocI8x16 = @Vector(16, i8);
pub const RocU16x8 = @Vector(8, u16);
pub const RocI16x8 = @Vector(8, i16);
pub const RocU32x4 = @Vector(4, u32);
pub const RocI32x4 = @Vector(4, i32);
pub const RocU64x2 = @Vector(2, u64);
pub const RocI64x2 = @Vector(2, i64);
comptime {
    for (.{ RocU8x16, RocI8x16, RocU16x8, RocI16x8, RocU32x4, RocI32x4, RocU64x2, RocI64x2 }) |T| {
        if (@sizeOf(T) != 16) @compileError("Roc SIMD size mismatch");
        if (@alignOf(T) != 16) @compileError("Roc SIMD alignment mismatch");
    }
}

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    /// Never returns null; see `roc_alloc` below.
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) *anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    /// Never returns null; see `roc_realloc` below.
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) *anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
///
/// The final `reuse` pointer is nullable. Non-null must be the callable data
/// pointer whose inline capture begins at `capture`; it transfers one owned
/// reference to the callee. The caller must not use or decref that ownership
/// unit after the call. The callee consumes it exactly once, whether or not the
/// result can reuse the allocation.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8, ?[*]u8, *?*const anyopaque) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocateBox(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) *anyopaque {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment));
    const data = base + header_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    return @ptrCast(data);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), false, null, roc_host);
}

/// Increment a boxed function closure.
pub fn increfErasedCallable(callable: RocErasedCallable, amount: isize) void {
    const data = callable orelse return;
    increfBox(@ptrCast(data), amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decrefErasedCallable(callable: RocErasedCallable, roc_host: *RocHost) void {
    const data = callable orelse return;
    decrefBoxWith(@ptrCast(data), roc_erased_callable_payload_alignment, false, &dropErasedCallablePayload, roc_host);
}

fn dropErasedCallablePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const data = data_ptr orelse return;
    const callable: RocErasedCallable = @ptrCast(data);
    const payload = rocErasedCallablePayloadPtr(callable);
    if (payload.on_drop) |on_drop| {
        on_drop(rocErasedCallableCapturePtr(callable), roc_host);
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocateBox`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted = false`
/// even when it provides a teardown callback to free the underlying resource.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_contains_refcounted, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decrefBoxWith` for the meaning of `payload_contains_refcounted`.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA—treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return every initialized element in the backing allocation.
        pub fn allocationItems(self: Self) []const T {
            const alloc_ptr = self.getAllocationPtr() orelse return &[_]T{};
            const count = self.allocationElementCount();
            const ptr: [*]const T = @ptrCast(@alignCast(alloc_ptr));
            return ptr[0..count];
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        fn allocationElementCount(self: Self) usize {
            if (self.isSeamlessSlice() and elements_refcounted) {
                const alloc_ptr = self.getAllocationPtr() orelse return 0;
                const ptr: [*]const usize = @ptrCast(@alignCast(alloc_ptr));
                return (ptr - 2)[0];
            }
            return self.length;
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            if (elements_refcounted) {
                const count: *usize = @ptrFromInt(@intFromPtr(data_ptr) - (2 * @sizeOf(usize)));
                count.* = length;
            }
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Drop this reference to the list allocation, freeing it when this was
        /// the last one.
        ///
        /// Shallow: it never touches the elements. To release an owned list whose
        /// elements are refcounted, call that list's generated `decrefListOf...`
        /// helper instead, which drops the elements when this reference is the
        /// last one and then calls this.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Recursively release this list and its elements.
        ///
        /// The reference-count decrement claims the final reference atomically
        /// before reading any elements, so concurrent releases cannot skip or
        /// duplicate element teardown.
        pub fn deinit(self: Self, roc_host: *RocHost) void {
            const ItemRelease = if (elements_refcounted) rocReleasePolicy(T) else RocNoopRelease(T);
            self.deinitWith(ItemRelease, roc_host);
        }

        /// Recursively release with an explicit compiler-generated item policy.
        pub fn deinitWith(self: Self, comptime ItemRelease: type, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—elements are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .acq_rel);
            if (prev == 1) {
                if (elements_refcounted) {
                    for (self.allocationItems()) |item| {
                        ItemRelease.release(item, roc_host);
                    }
                }
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA—treated as unique
            return rc.* == 1;
        }

        /// Return true if this list's allocation has exactly one counted ref.
        pub fn hasOneRef(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return false;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

pub fn RocNoopRelease(comptime T: type) type {
    return struct {
        pub fn release(value: T, roc_host: *RocHost) void {
            _ = value;
            _ = roc_host;
        }
    };
}

/// A zero-runtime-storage release policy for one Roc string.
pub const RocStrRelease = struct {
    pub fn release(value: RocStr, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

/// Compose a list release policy from its item release policy.
pub fn RocListRelease(comptime ListType: type, comptime ItemRelease: type) type {
    return struct {
        pub fn release(value: ListType, roc_host: *RocHost) void {
            value.deinitWith(ItemRelease, roc_host);
        }
    };
}

/// Release only a list spine whose elements contain no Roc references.
pub fn RocListSpineRelease(comptime ListType: type) type {
    return struct {
        pub fn release(value: ListType, roc_host: *RocHost) void {
            value.decref(roc_host);
        }
    };
}

pub const RocErasedCallableRelease = struct {
    pub fn release(value: RocErasedCallable, roc_host: *RocHost) void {
        decrefErasedCallable(value, roc_host);
    }
};

pub fn RocBoxRelease(comptime ValueType: type, comptime PayloadType: type, comptime PayloadRelease: type) type {
    return struct {
        fn releasePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
            const payload: *PayloadType = @ptrCast(@alignCast(data_ptr orelse return));
            PayloadRelease.release(payload.*, roc_host);
        }

        pub fn release(value: ValueType, roc_host: *RocHost) void {
            decrefBoxWith(@ptrCast(value), @alignOf(PayloadType), true, &releasePayload, roc_host);
        }
    };
}

pub fn RocBoxSpineRelease(comptime ValueType: type, comptime PayloadType: type) type {
    return struct {
        pub fn release(value: ValueType, roc_host: *RocHost) void {
            decrefBoxWith(@ptrCast(value), @alignOf(PayloadType), false, null, roc_host);
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct_82a96c5d55d63488
pub const __AnonStruct_82a96c5d55d63488 = if (@sizeOf(usize) == 4) extern struct {
    @"name": RocStr,
    @"value": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"name".decref(roc_host);
        value.@"value".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"name".incref(amount);
        value.@"value".incref(amount);
    }
} else extern struct {
    @"name": RocStr,
    @"value": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"name".decref(roc_host);
        value.@"value".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"name".incref(amount);
        value.@"value".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_82a96c5d55d63488) != 48) @compileError("__AnonStruct_82a96c5d55d63488 size mismatch");
        if (@alignOf(__AnonStruct_82a96c5d55d63488) != 8) @compileError("__AnonStruct_82a96c5d55d63488 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_82a96c5d55d63488) != 24) @compileError("__AnonStruct_82a96c5d55d63488 size mismatch");
        if (@alignOf(__AnonStruct_82a96c5d55d63488) != 4) @compileError("__AnonStruct_82a96c5d55d63488 alignment mismatch");
    }
}

/// Element type for __AnonStruct_2d568438e96cd20c
pub const __AnonStruct_2d568438e96cd20c = if (@sizeOf(usize) == 4) extern struct {
    @"columns": RocListWith(u8, false),
    @"name": RocStr,
    @"params": RocListWith(u8, false),
    @"sql": RocStr,
    @"rows_max": u32,
    @"writes": bool,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"columns".decref(roc_host);
        value.@"name".decref(roc_host);
        value.@"params".decref(roc_host);
        value.@"sql".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"columns".incref(amount);
        value.@"name".incref(amount);
        value.@"params".incref(amount);
        value.@"sql".incref(amount);
    }
} else extern struct {
    @"columns": RocListWith(u8, false),
    @"name": RocStr,
    @"params": RocListWith(u8, false),
    @"sql": RocStr,
    @"rows_max": u32,
    @"writes": bool,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"columns".decref(roc_host);
        value.@"name".decref(roc_host);
        value.@"params".decref(roc_host);
        value.@"sql".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"columns".incref(amount);
        value.@"name".incref(amount);
        value.@"params".incref(amount);
        value.@"sql".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_2d568438e96cd20c) != 104) @compileError("__AnonStruct_2d568438e96cd20c size mismatch");
        if (@alignOf(__AnonStruct_2d568438e96cd20c) != 8) @compileError("__AnonStruct_2d568438e96cd20c alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_2d568438e96cd20c) != 56) @compileError("__AnonStruct_2d568438e96cd20c size mismatch");
        if (@alignOf(__AnonStruct_2d568438e96cd20c) != 4) @compileError("__AnonStruct_2d568438e96cd20c alignment mismatch");
    }
}

/// Element type for __AnonStruct_4c605145331877e7
pub const __AnonStruct_4c605145331877e7 = if (@sizeOf(usize) == 4) extern struct {
    @"message": RocStr,
    @"code": u8,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"message".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"message".incref(amount);
    }
} else extern struct {
    @"message": RocStr,
    @"code": u8,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"message".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"message".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_4c605145331877e7) != 32) @compileError("__AnonStruct_4c605145331877e7 size mismatch");
        if (@alignOf(__AnonStruct_4c605145331877e7) != 8) @compileError("__AnonStruct_4c605145331877e7 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_4c605145331877e7) != 16) @compileError("__AnonStruct_4c605145331877e7 size mismatch");
        if (@alignOf(__AnonStruct_4c605145331877e7) != 4) @compileError("__AnonStruct_4c605145331877e7 alignment mismatch");
    }
}

/// Element type for __AnonStruct_2a70a3dd551fa8a1
pub const __AnonStruct_2a70a3dd551fa8a1 = if (@sizeOf(usize) == 4) extern struct {
    @"context": RocBox,
    @"static_dir": RocStr,
    @"port": u16,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefBox(@ptrCast(value.@"context"), roc_host);
        value.@"static_dir".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        increfBox(@ptrCast(value.@"context"), amount);
        value.@"static_dir".incref(amount);
    }
} else extern struct {
    @"context": RocBox,
    @"static_dir": RocStr,
    @"port": u16,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefBox(@ptrCast(value.@"context"), roc_host);
        value.@"static_dir".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        increfBox(@ptrCast(value.@"context"), amount);
        value.@"static_dir".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_2a70a3dd551fa8a1) != 40) @compileError("__AnonStruct_2a70a3dd551fa8a1 size mismatch");
        if (@alignOf(__AnonStruct_2a70a3dd551fa8a1) != 8) @compileError("__AnonStruct_2a70a3dd551fa8a1 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_2a70a3dd551fa8a1) != 20) @compileError("__AnonStruct_2a70a3dd551fa8a1 size mismatch");
        if (@alignOf(__AnonStruct_2a70a3dd551fa8a1) != 4) @compileError("__AnonStruct_2a70a3dd551fa8a1 alignment mismatch");
    }
}

/// Element type for __AnonStruct_a14cd3b7d5755441
pub const __AnonStruct_a14cd3b7d5755441 = if (@sizeOf(usize) == 4) extern struct {
    @"body": RocListWith(u8, false),
    @"headers": RocList(__AnonStruct_82a96c5d55d63488),
    @"status": u16,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"body".decref(roc_host);
        decrefListOf__AnonStruct_82a96c5d55d63488(value.@"headers", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"body".incref(amount);
        value.@"headers".incref(amount);
    }
} else extern struct {
    @"body": RocListWith(u8, false),
    @"headers": RocList(__AnonStruct_82a96c5d55d63488),
    @"status": u16,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"body".decref(roc_host);
        decrefListOf__AnonStruct_82a96c5d55d63488(value.@"headers", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"body".incref(amount);
        value.@"headers".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_a14cd3b7d5755441) != 56) @compileError("__AnonStruct_a14cd3b7d5755441 size mismatch");
        if (@alignOf(__AnonStruct_a14cd3b7d5755441) != 8) @compileError("__AnonStruct_a14cd3b7d5755441 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_a14cd3b7d5755441) != 28) @compileError("__AnonStruct_a14cd3b7d5755441 size mismatch");
        if (@alignOf(__AnonStruct_a14cd3b7d5755441) != 4) @compileError("__AnonStruct_a14cd3b7d5755441 alignment mismatch");
    }
}

/// Element type for __AnonStruct_28781edfe447a702
pub const __AnonStruct_28781edfe447a702 = if (@sizeOf(usize) == 4) extern struct {
    @"body": u64,
    @"headers": RocList(__AnonStruct_82a96c5d55d63488),
    @"method": RocStr,
    @"target": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_82a96c5d55d63488(value.@"headers", roc_host);
        value.@"method".decref(roc_host);
        value.@"target".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"headers".incref(amount);
        value.@"method".incref(amount);
        value.@"target".incref(amount);
    }
} else extern struct {
    @"body": u64,
    @"headers": RocList(__AnonStruct_82a96c5d55d63488),
    @"method": RocStr,
    @"target": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_82a96c5d55d63488(value.@"headers", roc_host);
        value.@"method".decref(roc_host);
        value.@"target".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"headers".incref(amount);
        value.@"method".incref(amount);
        value.@"target".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_28781edfe447a702) != 80) @compileError("__AnonStruct_28781edfe447a702 size mismatch");
        if (@alignOf(__AnonStruct_28781edfe447a702) != 8) @compileError("__AnonStruct_28781edfe447a702 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_28781edfe447a702) != 48) @compileError("__AnonStruct_28781edfe447a702 size mismatch");
        if (@alignOf(__AnonStruct_28781edfe447a702) != 8) @compileError("__AnonStruct_28781edfe447a702 alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostFile_read_utf8ResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostFile_read_utf8ResultPayload = extern union {
        @"err": FileNotFoundOrFileTooLargeOrFileUnreadable,
        @"ok": RocStr,
};

/// Tag union: Try
pub const HostFile_read_utf8Result = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostFile_read_utf8ResultTag,
    pub fn payload_err(self: *const @This()) FileNotFoundOrFileTooLargeOrFileUnreadable {
        const ptr: *const FileNotFoundOrFileTooLargeOrFileUnreadable = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ok(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_read_utf8Result(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_read_utf8Result(self, amount);
    }
} else extern struct {
    payload: HostFile_read_utf8ResultPayload,
    tag: HostFile_read_utf8ResultTag,
    pub fn payload_err(self: *const @This()) FileNotFoundOrFileTooLargeOrFileUnreadable {
        return self.payload.@"err";
    }
    pub fn payload_ok(self: *const @This()) RocStr {
        return self.payload.@"ok";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_read_utf8Result(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_read_utf8Result(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostFile_read_utf8Result) != 32) @compileError("HostFile_read_utf8Result size mismatch");
        if (@alignOf(HostFile_read_utf8Result) != 8) @compileError("HostFile_read_utf8Result alignment mismatch");
        if (@offsetOf(HostFile_read_utf8Result, "tag") != 24) @compileError("HostFile_read_utf8Result tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostFile_read_utf8Result) != 16) @compileError("HostFile_read_utf8Result size mismatch");
        if (@alignOf(HostFile_read_utf8Result) != 4) @compileError("HostFile_read_utf8Result alignment mismatch");
        if (@offsetOf(HostFile_read_utf8Result, "tag") != 12) @compileError("HostFile_read_utf8Result tag offset mismatch");
    }
}

/// Tag union: FileNotFoundOrFileTooLargeOrFileUnreadable
pub const FileNotFoundOrFileTooLargeOrFileUnreadable = enum(u8) {
    @"file_not_found" = 0,
    @"file_too_large" = 1,
    @"file_unreadable" = 2,
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        _ = self;
        _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        _ = self;
        _ = amount;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(FileNotFoundOrFileTooLargeOrFileUnreadable) != 1) @compileError("FileNotFoundOrFileTooLargeOrFileUnreadable size mismatch");
        if (@alignOf(FileNotFoundOrFileTooLargeOrFileUnreadable) != 1) @compileError("FileNotFoundOrFileTooLargeOrFileUnreadable alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(FileNotFoundOrFileTooLargeOrFileUnreadable) != 1) @compileError("FileNotFoundOrFileTooLargeOrFileUnreadable size mismatch");
        if (@alignOf(FileNotFoundOrFileTooLargeOrFileUnreadable) != 1) @compileError("FileNotFoundOrFileTooLargeOrFileUnreadable alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostRequest_body_read_allResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostRequest_body_read_allResultPayload = extern union {
        @"err": BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge,
        @"ok": RocListWith(u8, false),
};

/// Tag union: Try
pub const HostRequest_body_read_allResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostRequest_body_read_allResultTag,
    pub fn payload_err(self: *const @This()) BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge {
        const ptr: *const BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ok(self: *const @This()) RocListWith(u8, false) {
        const ptr: *const RocListWith(u8, false) = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostRequest_body_read_allResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostRequest_body_read_allResult(self, amount);
    }
} else extern struct {
    payload: HostRequest_body_read_allResultPayload,
    tag: HostRequest_body_read_allResultTag,
    pub fn payload_err(self: *const @This()) BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge {
        return self.payload.@"err";
    }
    pub fn payload_ok(self: *const @This()) RocListWith(u8, false) {
        return self.payload.@"ok";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostRequest_body_read_allResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostRequest_body_read_allResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostRequest_body_read_allResult) != 32) @compileError("HostRequest_body_read_allResult size mismatch");
        if (@alignOf(HostRequest_body_read_allResult) != 8) @compileError("HostRequest_body_read_allResult alignment mismatch");
        if (@offsetOf(HostRequest_body_read_allResult, "tag") != 24) @compileError("HostRequest_body_read_allResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostRequest_body_read_allResult) != 16) @compileError("HostRequest_body_read_allResult size mismatch");
        if (@alignOf(HostRequest_body_read_allResult) != 4) @compileError("HostRequest_body_read_allResult alignment mismatch");
        if (@offsetOf(HostRequest_body_read_allResult, "tag") != 12) @compileError("HostRequest_body_read_allResult tag offset mismatch");
    }
}

/// Tag union: BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge
pub const BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge = enum(u8) {
    @"body_after_stream" = 0,
    @"body_disconnected" = 1,
    @"body_during_write" = 2,
    @"body_invalid" = 3,
    @"body_too_large" = 4,
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        _ = self;
        _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        _ = self;
        _ = amount;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge) != 1) @compileError("BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge size mismatch");
        if (@alignOf(BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge) != 1) @compileError("BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge) != 1) @compileError("BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge size mismatch");
        if (@alignOf(BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge) != 1) @compileError("BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostResponse_stream_startResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostResponse_stream_startResultPayload = extern union {
        @"err": StreamDisconnectedOrStreamRefused,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostResponse_stream_startResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [1]u8 align(1),
    tag: HostResponse_stream_startResultTag,
    pub fn payload_err(self: *const @This()) StreamDisconnectedOrStreamRefused {
        const ptr: *const StreamDisconnectedOrStreamRefused = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostResponse_stream_startResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostResponse_stream_startResult(self, amount);
    }
} else extern struct {
    payload: HostResponse_stream_startResultPayload,
    tag: HostResponse_stream_startResultTag,
    pub fn payload_err(self: *const @This()) StreamDisconnectedOrStreamRefused {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostResponse_stream_startResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostResponse_stream_startResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostResponse_stream_startResult) != 2) @compileError("HostResponse_stream_startResult size mismatch");
        if (@alignOf(HostResponse_stream_startResult) != 1) @compileError("HostResponse_stream_startResult alignment mismatch");
        if (@offsetOf(HostResponse_stream_startResult, "tag") != 1) @compileError("HostResponse_stream_startResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostResponse_stream_startResult) != 2) @compileError("HostResponse_stream_startResult size mismatch");
        if (@alignOf(HostResponse_stream_startResult) != 1) @compileError("HostResponse_stream_startResult alignment mismatch");
        if (@offsetOf(HostResponse_stream_startResult, "tag") != 1) @compileError("HostResponse_stream_startResult tag offset mismatch");
    }
}

/// Tag union: StreamDisconnectedOrStreamRefused
pub const StreamDisconnectedOrStreamRefused = enum(u8) {
    @"stream_disconnected" = 0,
    @"stream_refused" = 1,
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        _ = self;
        _ = roc_host;
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        _ = self;
        _ = amount;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(StreamDisconnectedOrStreamRefused) != 1) @compileError("StreamDisconnectedOrStreamRefused size mismatch");
        if (@alignOf(StreamDisconnectedOrStreamRefused) != 1) @compileError("StreamDisconnectedOrStreamRefused alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(StreamDisconnectedOrStreamRefused) != 1) @compileError("StreamDisconnectedOrStreamRefused size mismatch");
        if (@alignOf(StreamDisconnectedOrStreamRefused) != 1) @compileError("StreamDisconnectedOrStreamRefused alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostSqlite_openResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostSqlite_openResultPayload = extern union {
        @"err": RocStr,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostSqlite_openResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostSqlite_openResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_openResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_openResult(self, amount);
    }
} else extern struct {
    payload: HostSqlite_openResultPayload,
    tag: HostSqlite_openResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_openResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_openResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostSqlite_openResult) != 32) @compileError("HostSqlite_openResult size mismatch");
        if (@alignOf(HostSqlite_openResult) != 8) @compileError("HostSqlite_openResult alignment mismatch");
        if (@offsetOf(HostSqlite_openResult, "tag") != 24) @compileError("HostSqlite_openResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostSqlite_openResult) != 16) @compileError("HostSqlite_openResult size mismatch");
        if (@alignOf(HostSqlite_openResult) != 4) @compileError("HostSqlite_openResult alignment mismatch");
        if (@offsetOf(HostSqlite_openResult, "tag") != 12) @compileError("HostSqlite_openResult tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostSqlite_runResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostSqlite_runResultPayload = extern union {
        @"err": __AnonStruct_4c605145331877e7,
        @"ok": RocList(RocList(BlobOrIntegerOrNullOrRealOrText)),
};

/// Tag union: Try
pub const HostSqlite_runResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [16]u8 align(4),
    tag: HostSqlite_runResultTag,
    pub fn payload_err(self: *const @This()) __AnonStruct_4c605145331877e7 {
        const ptr: *const __AnonStruct_4c605145331877e7 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ok(self: *const @This()) RocList(RocList(BlobOrIntegerOrNullOrRealOrText)) {
        const ptr: *const RocList(RocList(BlobOrIntegerOrNullOrRealOrText)) = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_runResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_runResult(self, amount);
    }
} else extern struct {
    payload: HostSqlite_runResultPayload,
    tag: HostSqlite_runResultTag,
    pub fn payload_err(self: *const @This()) __AnonStruct_4c605145331877e7 {
        return self.payload.@"err";
    }
    pub fn payload_ok(self: *const @This()) RocList(RocList(BlobOrIntegerOrNullOrRealOrText)) {
        return self.payload.@"ok";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_runResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_runResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostSqlite_runResult) != 40) @compileError("HostSqlite_runResult size mismatch");
        if (@alignOf(HostSqlite_runResult) != 8) @compileError("HostSqlite_runResult alignment mismatch");
        if (@offsetOf(HostSqlite_runResult, "tag") != 32) @compileError("HostSqlite_runResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostSqlite_runResult) != 20) @compileError("HostSqlite_runResult size mismatch");
        if (@alignOf(HostSqlite_runResult) != 4) @compileError("HostSqlite_runResult alignment mismatch");
        if (@offsetOf(HostSqlite_runResult, "tag") != 16) @compileError("HostSqlite_runResult tag offset mismatch");
    }
}

/// Tag discriminant for BlobOrIntegerOrNullOrRealOrText.
pub const BlobOrIntegerOrNullOrRealOrTextTag = enum(u8) {
    @"Blob" = 0,
    @"Integer" = 1,
    @"Null" = 2,
    @"Real" = 3,
    @"Text" = 4,
};

/// Payload union for BlobOrIntegerOrNullOrRealOrText.
pub const BlobOrIntegerOrNullOrRealOrTextPayload = extern union {
        @"blob": RocListWith(u8, false),
        @"integer": i64,
        @"null": [0]u8,
        @"real": f64,
        @"text": RocStr,
};

/// Tag union: BlobOrIntegerOrNullOrRealOrText
pub const BlobOrIntegerOrNullOrRealOrText = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(8),
    tag: BlobOrIntegerOrNullOrRealOrTextTag,
    pub fn payload_blob(self: *const @This()) RocListWith(u8, false) {
        const ptr: *const RocListWith(u8, false) = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_integer(self: *const @This()) i64 {
        const ptr: *const i64 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_real(self: *const @This()) f64 {
        const ptr: *const f64 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_text(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefBlobOrIntegerOrNullOrRealOrText(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfBlobOrIntegerOrNullOrRealOrText(self, amount);
    }
} else extern struct {
    payload: BlobOrIntegerOrNullOrRealOrTextPayload,
    tag: BlobOrIntegerOrNullOrRealOrTextTag,
    pub fn payload_blob(self: *const @This()) RocListWith(u8, false) {
        return self.payload.@"blob";
    }
    pub fn payload_integer(self: *const @This()) i64 {
        return self.payload.@"integer";
    }
    pub fn payload_real(self: *const @This()) f64 {
        return self.payload.@"real";
    }
    pub fn payload_text(self: *const @This()) RocStr {
        return self.payload.@"text";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefBlobOrIntegerOrNullOrRealOrText(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfBlobOrIntegerOrNullOrRealOrText(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(BlobOrIntegerOrNullOrRealOrText) != 32) @compileError("BlobOrIntegerOrNullOrRealOrText size mismatch");
        if (@alignOf(BlobOrIntegerOrNullOrRealOrText) != 8) @compileError("BlobOrIntegerOrNullOrRealOrText alignment mismatch");
        if (@offsetOf(BlobOrIntegerOrNullOrRealOrText, "tag") != 24) @compileError("BlobOrIntegerOrNullOrRealOrText tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(BlobOrIntegerOrNullOrRealOrText) != 16) @compileError("BlobOrIntegerOrNullOrRealOrText size mismatch");
        if (@alignOf(BlobOrIntegerOrNullOrRealOrText) != 8) @compileError("BlobOrIntegerOrNullOrRealOrText alignment mismatch");
        if (@offsetOf(BlobOrIntegerOrNullOrRealOrText, "tag") != 12) @compileError("BlobOrIntegerOrNullOrRealOrText tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostSqlite_write_beginResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostSqlite_write_beginResultPayload = extern union {
        @"err": __AnonStruct_4c605145331877e7,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostSqlite_write_beginResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [16]u8 align(4),
    tag: HostSqlite_write_beginResultTag,
    pub fn payload_err(self: *const @This()) __AnonStruct_4c605145331877e7 {
        const ptr: *const __AnonStruct_4c605145331877e7 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_write_beginResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_write_beginResult(self, amount);
    }
} else extern struct {
    payload: HostSqlite_write_beginResultPayload,
    tag: HostSqlite_write_beginResultTag,
    pub fn payload_err(self: *const @This()) __AnonStruct_4c605145331877e7 {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostSqlite_write_beginResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostSqlite_write_beginResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostSqlite_write_beginResult) != 40) @compileError("HostSqlite_write_beginResult size mismatch");
        if (@alignOf(HostSqlite_write_beginResult) != 8) @compileError("HostSqlite_write_beginResult alignment mismatch");
        if (@offsetOf(HostSqlite_write_beginResult, "tag") != 32) @compileError("HostSqlite_write_beginResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostSqlite_write_beginResult) != 20) @compileError("HostSqlite_write_beginResult size mismatch");
        if (@alignOf(HostSqlite_write_beginResult) != 4) @compileError("HostSqlite_write_beginResult alignment mismatch");
        if (@offsetOf(HostSqlite_write_beginResult, "tag") != 16) @compileError("HostSqlite_write_beginResult tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const Init_for_hostResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const Init_for_hostResultPayload = extern union {
        @"err": i64,
        @"ok": __AnonStruct_2a70a3dd551fa8a1,
};

/// Tag union: Try
pub const Init_for_hostResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [20]u8 align(8),
    tag: Init_for_hostResultTag,
    pub fn payload_err(self: *const @This()) i64 {
        const ptr: *const i64 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ok(self: *const @This()) __AnonStruct_2a70a3dd551fa8a1 {
        const ptr: *const __AnonStruct_2a70a3dd551fa8a1 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefInit_for_hostResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfInit_for_hostResult(self, amount);
    }
} else extern struct {
    payload: Init_for_hostResultPayload,
    tag: Init_for_hostResultTag,
    pub fn payload_err(self: *const @This()) i64 {
        return self.payload.@"err";
    }
    pub fn payload_ok(self: *const @This()) __AnonStruct_2a70a3dd551fa8a1 {
        return self.payload.@"ok";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefInit_for_hostResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfInit_for_hostResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Init_for_hostResult) != 48) @compileError("Init_for_hostResult size mismatch");
        if (@alignOf(Init_for_hostResult) != 8) @compileError("Init_for_hostResult alignment mismatch");
        if (@offsetOf(Init_for_hostResult, "tag") != 40) @compileError("Init_for_hostResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(Init_for_hostResult) != 24) @compileError("Init_for_hostResult size mismatch");
        if (@alignOf(Init_for_hostResult) != 8) @compileError("Init_for_hostResult alignment mismatch");
        if (@offsetOf(Init_for_hostResult, "tag") != 20) @compileError("Init_for_hostResult tag offset mismatch");
    }
}

/// Arguments for Host.stdout_line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostStdout_lineArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.stderr_line!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostStderr_lineArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.file_read_utf8!
/// Roc signature: Str, U64 => Try(Str, [FileNotFound, FileTooLarge, FileUnreadable])
/// Refcounted fields are owned by the hosted function.
pub const HostFile_read_utf8Args = extern struct {
    arg0: RocStr,
    arg1: u64,
};

/// Arguments for Host.request_body_read_all!
/// Roc signature: U64, U64 => Try(List(U8), [BodyAfterStream, BodyDisconnected, BodyDuringWrite, BodyInvalid, BodyTooLarge])
/// Refcounted fields are owned by the hosted function.
pub const HostRequest_body_read_allArgs = extern struct {
    arg0: u64,
    arg1: u64,
};

/// Arguments for Host.response_stream_start!
/// Roc signature: U64, List({ name : Str, value : Str }) => Try({}, [StreamDisconnected, StreamRefused])
/// Refcounted fields are owned by the hosted function.
pub const HostResponse_stream_startArgs = extern struct {
    arg0: u64,
    arg1: RocList(__AnonStruct_82a96c5d55d63488),
};

/// Arguments for Host.response_stream_send!
/// Roc signature: U64, List(U8) => Try({}, [StreamDisconnected, StreamRefused])
/// Refcounted fields are owned by the hosted function.
pub const HostResponse_stream_sendArgs = extern struct {
    arg0: u64,
    arg1: RocListWith(u8, false),
};

/// Arguments for Host.response_stream_flush!
/// Roc signature: U64 => Try({}, [StreamDisconnected, StreamRefused])
/// Refcounted fields are owned by the hosted function.
pub const HostResponse_stream_flushArgs = extern struct {
    arg0: u64,
};

/// Arguments for Host.response_stream_end!
/// Roc signature: U64 => Try({}, [StreamDisconnected, StreamRefused])
/// Refcounted fields are owned by the hosted function.
pub const HostResponse_stream_endArgs = extern struct {
    arg0: u64,
};

/// Arguments for Host.sqlite_open!
/// Roc signature: Str, Str, List({ columns : List(U8), name : Str, params : List(U8), rows_max : U32, sql : Str, writes : Bool }) => Try({}, Str)
/// Refcounted fields are owned by the hosted function.
pub const HostSqlite_openArgs = extern struct {
    arg0: RocStr,
    arg1: RocStr,
    arg2: RocList(__AnonStruct_2d568438e96cd20c),
};

/// Arguments for Host.sqlite_run!
/// Roc signature: U64, U32, Bool, List([Blob(List(U8)), Integer(I64), Null, Real(F64), Text(Str)]) => Try(List(List([Blob(List(U8)), Integer(I64), Null, Real(F64), Text(Str)])), { code : U8, message : Str })
/// Refcounted fields are owned by the hosted function.
pub const HostSqlite_runArgs = extern struct {
    arg0: u64,
    arg1: u32,
    arg2: bool,
    arg3: RocList(BlobOrIntegerOrNullOrRealOrText),
};

/// Arguments for Host.sqlite_write_begin!
/// Roc signature: U64 => Try({}, { code : U8, message : Str })
/// Refcounted fields are owned by the hosted function.
pub const HostSqlite_write_beginArgs = extern struct {
    arg0: u64,
};

/// Arguments for Host.sqlite_commit!
/// Roc signature: U64 => Try({}, { code : U8, message : Str })
/// Refcounted fields are owned by the hosted function.
pub const HostSqlite_commitArgs = extern struct {
    arg0: u64,
};

// Platform Type Aliases

pub const HostFile_read_utf8Err = FileNotFoundOrFileTooLargeOrFileUnreadable;
pub const HostRequest_body_read_allErr = BodyAfterStreamOrBodyDisconnectedOrBodyDuringWriteOrBodyInvalidOrBodyTooLarge;
pub const HostResponse_stream_startArg1 = __AnonStruct_82a96c5d55d63488;
pub const HostResponse_stream_startErr = StreamDisconnectedOrStreamRefused;
pub const HostResponse_stream_sendResult = HostResponse_stream_startResult;
pub const HostResponse_stream_sendResultPayload = HostResponse_stream_startResultPayload;
pub const HostResponse_stream_sendResultTag = HostResponse_stream_startResultTag;
pub const HostResponse_stream_sendErr = StreamDisconnectedOrStreamRefused;
pub const HostResponse_stream_flushResult = HostResponse_stream_startResult;
pub const HostResponse_stream_flushResultPayload = HostResponse_stream_startResultPayload;
pub const HostResponse_stream_flushResultTag = HostResponse_stream_startResultTag;
pub const HostResponse_stream_flushErr = StreamDisconnectedOrStreamRefused;
pub const HostResponse_stream_endResult = HostResponse_stream_startResult;
pub const HostResponse_stream_endResultPayload = HostResponse_stream_startResultPayload;
pub const HostResponse_stream_endResultTag = HostResponse_stream_startResultTag;
pub const HostResponse_stream_endErr = StreamDisconnectedOrStreamRefused;
pub const HostSqlite_openArg2 = __AnonStruct_2d568438e96cd20c;
pub const HostSqlite_runArg3 = BlobOrIntegerOrNullOrRealOrText;
pub const HostSqlite_runArg3Payload = BlobOrIntegerOrNullOrRealOrTextPayload;
pub const HostSqlite_runArg3Tag = BlobOrIntegerOrNullOrRealOrTextTag;
pub const HostSqlite_runErr = __AnonStruct_4c605145331877e7;
pub const HostSqlite_runOk = BlobOrIntegerOrNullOrRealOrText;
pub const HostSqlite_runOkPayload = BlobOrIntegerOrNullOrRealOrTextPayload;
pub const HostSqlite_runOkTag = BlobOrIntegerOrNullOrRealOrTextTag;
pub const HostSqlite_write_beginErr = __AnonStruct_4c605145331877e7;
pub const HostSqlite_commitResult = HostSqlite_write_beginResult;
pub const HostSqlite_commitResultPayload = HostSqlite_write_beginResultPayload;
pub const HostSqlite_commitResultTag = HostSqlite_write_beginResultTag;
pub const HostSqlite_commitErr = __AnonStruct_4c605145331877e7;
pub const Init_for_hostOk = __AnonStruct_2a70a3dd551fa8a1;
pub const Respond_for_hostArg0 = __AnonStruct_28781edfe447a702;
pub const Respond_for_hostArg0Headers = __AnonStruct_82a96c5d55d63488;
pub const Respond_for_host = __AnonStruct_a14cd3b7d5755441;
pub const Respond_for_hostHeaders = __AnonStruct_82a96c5d55d63488;

// Generated Refcount Helpers

fn decrefHostFile_read_utf8Result(value: HostFile_read_utf8Result, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {
        value.payload_ok().decref(roc_host);
        },
    }
}

fn increfHostFile_read_utf8Result(value: HostFile_read_utf8Result, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {
        value.payload_ok().incref(amount);
        },
    }
}

pub const HostFile_read_utf8ResultRelease = struct {
    pub fn release(value: HostFile_read_utf8Result, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostRequest_body_read_allResult(value: HostRequest_body_read_allResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {
        value.payload_ok().decref(roc_host);
        },
    }
}

fn increfHostRequest_body_read_allResult(value: HostRequest_body_read_allResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {
        value.payload_ok().incref(amount);
        },
    }
}

pub const HostRequest_body_read_allResultRelease = struct {
    pub fn release(value: HostRequest_body_read_allResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostResponse_stream_startResult(value: HostResponse_stream_startResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostResponse_stream_startResult(value: HostResponse_stream_startResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostResponse_stream_startResultRelease = struct {
    pub fn release(value: HostResponse_stream_startResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_82a96c5d55d63488Release = struct {
    pub fn release(value: __AnonStruct_82a96c5d55d63488, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostSqlite_openResult(value: HostSqlite_openResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostSqlite_openResult(value: HostSqlite_openResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostSqlite_openResultRelease = struct {
    pub fn release(value: HostSqlite_openResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_2d568438e96cd20cRelease = struct {
    pub fn release(value: __AnonStruct_2d568438e96cd20c, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostSqlite_runResult(value: HostSqlite_runResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {
        decrefListOfListOfBlobOrIntegerOrNullOrRealOrText(value.payload_ok(), roc_host);
        },
    }
}

fn increfHostSqlite_runResult(value: HostSqlite_runResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {
        value.payload_ok().incref(amount);
        },
    }
}

pub const HostSqlite_runResultRelease = struct {
    pub fn release(value: HostSqlite_runResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_4c605145331877e7Release = struct {
    pub fn release(value: __AnonStruct_4c605145331877e7, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefBlobOrIntegerOrNullOrRealOrText(value: BlobOrIntegerOrNullOrRealOrText, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Blob" => {
        value.payload_blob().decref(roc_host);
        },
        .@"Integer" => {},
        .@"Null" => {},
        .@"Real" => {},
        .@"Text" => {
        value.payload_text().decref(roc_host);
        },
    }
}

fn increfBlobOrIntegerOrNullOrRealOrText(value: BlobOrIntegerOrNullOrRealOrText, amount: isize) void {
    switch (value.tag) {
        .@"Blob" => {
        value.payload_blob().incref(amount);
        },
        .@"Integer" => {},
        .@"Null" => {},
        .@"Real" => {},
        .@"Text" => {
        value.payload_text().incref(amount);
        },
    }
}

pub const BlobOrIntegerOrNullOrRealOrTextRelease = struct {
    pub fn release(value: BlobOrIntegerOrNullOrRealOrText, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostSqlite_write_beginResult(value: HostSqlite_write_beginResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostSqlite_write_beginResult(value: HostSqlite_write_beginResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostSqlite_write_beginResultRelease = struct {
    pub fn release(value: HostSqlite_write_beginResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefInit_for_hostResult(value: Init_for_hostResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {},
        .@"Ok" => {
        value.payload_ok().decref(roc_host);
        },
    }
}

fn increfInit_for_hostResult(value: Init_for_hostResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {},
        .@"Ok" => {
        value.payload_ok().incref(amount);
        },
    }
}

pub const Init_for_hostResultRelease = struct {
    pub fn release(value: Init_for_hostResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_2a70a3dd551fa8a1Release = struct {
    pub fn release(value: __AnonStruct_2a70a3dd551fa8a1, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_a14cd3b7d5755441Release = struct {
    pub fn release(value: __AnonStruct_a14cd3b7d5755441, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_28781edfe447a702Release = struct {
    pub fn release(value: __AnonStruct_28781edfe447a702, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

/// Release one owned reference to a `RocList(__AnonStruct_82a96c5d55d63488)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOf__AnonStruct_82a96c5d55d63488(value: RocList(__AnonStruct_82a96c5d55d63488), roc_host: *RocHost) void {
    value.deinitWith(__AnonStruct_82a96c5d55d63488Release, roc_host);
}

/// Release one owned reference to a `RocList(__AnonStruct_2d568438e96cd20c)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOf__AnonStruct_2d568438e96cd20c(value: RocList(__AnonStruct_2d568438e96cd20c), roc_host: *RocHost) void {
    value.deinitWith(__AnonStruct_2d568438e96cd20cRelease, roc_host);
}

/// Release one owned reference to a `RocList(RocList(BlobOrIntegerOrNullOrRealOrText))`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOfListOfBlobOrIntegerOrNullOrRealOrText(value: RocList(RocList(BlobOrIntegerOrNullOrRealOrText)), roc_host: *RocHost) void {
    value.deinitWith(RocListRelease(RocList(BlobOrIntegerOrNullOrRealOrText), BlobOrIntegerOrNullOrRealOrTextRelease), roc_host);
}

/// Release one owned reference to a `RocList(BlobOrIntegerOrNullOrRealOrText)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOfBlobOrIntegerOrNullOrRealOrText(value: RocList(BlobOrIntegerOrNullOrRealOrText), roc_host: *RocHost) void {
    value.deinitWith(BlobOrIntegerOrNullOrRealOrTextRelease, roc_host);
}


fn rocReleasePolicy(comptime T: type) type {
    if (T == RocStr) return RocStrRelease;
    if (T == HostFile_read_utf8Result) return HostFile_read_utf8ResultRelease;
    if (T == HostRequest_body_read_allResult) return HostRequest_body_read_allResultRelease;
    if (T == RocListWith(u8, false)) return RocListSpineRelease(RocListWith(u8, false));
    if (T == RocList(__AnonStruct_82a96c5d55d63488)) return RocListRelease(RocList(__AnonStruct_82a96c5d55d63488), __AnonStruct_82a96c5d55d63488Release);
    if (T == __AnonStruct_82a96c5d55d63488) return __AnonStruct_82a96c5d55d63488Release;
    if (T == HostSqlite_openResult) return HostSqlite_openResultRelease;
    if (T == RocList(__AnonStruct_2d568438e96cd20c)) return RocListRelease(RocList(__AnonStruct_2d568438e96cd20c), __AnonStruct_2d568438e96cd20cRelease);
    if (T == __AnonStruct_2d568438e96cd20c) return __AnonStruct_2d568438e96cd20cRelease;
    if (T == HostSqlite_runResult) return HostSqlite_runResultRelease;
    if (T == __AnonStruct_4c605145331877e7) return __AnonStruct_4c605145331877e7Release;
    if (T == RocList(RocList(BlobOrIntegerOrNullOrRealOrText))) return RocListRelease(RocList(RocList(BlobOrIntegerOrNullOrRealOrText)), RocListRelease(RocList(BlobOrIntegerOrNullOrRealOrText), BlobOrIntegerOrNullOrRealOrTextRelease));
    if (T == RocList(BlobOrIntegerOrNullOrRealOrText)) return RocListRelease(RocList(BlobOrIntegerOrNullOrRealOrText), BlobOrIntegerOrNullOrRealOrTextRelease);
    if (T == BlobOrIntegerOrNullOrRealOrText) return BlobOrIntegerOrNullOrRealOrTextRelease;
    if (T == HostSqlite_write_beginResult) return HostSqlite_write_beginResultRelease;
    if (T == Init_for_hostResult) return Init_for_hostResultRelease;
    if (T == __AnonStruct_2a70a3dd551fa8a1) return __AnonStruct_2a70a3dd551fa8a1Release;
    if (T == __AnonStruct_a14cd3b7d5755441) return __AnonStruct_a14cd3b7d5755441Release;
    if (T == __AnonStruct_28781edfe447a702) return __AnonStruct_28781edfe447a702Release;
    @compileError("generated glue has no recursive release policy for " ++ @typeName(T));
}


// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.

/// Returns `length` bytes aligned to `alignment`. Never returns null: Roc writes through
/// the result without checking it, so a host that cannot allocate must stop the Roc
/// program and not return, exactly as `roc_crashed` does.
pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) *anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
/// Never returns null, under the same rule as `roc_alloc`.
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) *anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
/// Must never return: end the process, or longjmp out of the Roc code that called
/// it. Roc code traps right after this call, so returning terminates the process.
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.

/// Hosted symbol for Host.stdout_line!
/// Roc signature: Str => {}
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn hosted_stdout_line(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.stderr_line!
/// Roc signature: Str => {}
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn hosted_stderr_line(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.file_read_utf8!
/// Roc signature: Str, U64 => Try(Str, [FileNotFound, FileTooLarge, FileUnreadable])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_file_read_utf8(arg0: RocStr, arg1: u64) callconv(.c) HostFile_read_utf8Result;

/// Hosted symbol for Host.request_body_read_all!
/// Roc signature: U64, U64 => Try(List(U8), [BodyAfterStream, BodyDisconnected, BodyDuringWrite, BodyInvalid, BodyTooLarge])
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_request_body_read_all(arg0: u64, arg1: u64) callconv(.c) HostRequest_body_read_allResult;

/// Hosted symbol for Host.response_stream_start!
/// Roc signature: U64, List({ name : Str, value : Str }) => Try({}, [StreamDisconnected, StreamRefused])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     decrefListOf__AnonStruct_82a96c5d55d63488(arg1, roc_host);
pub extern fn hosted_response_stream_start(arg0: u64, arg1: RocList(__AnonStruct_82a96c5d55d63488)) callconv(.c) HostResponse_stream_startResult;

/// Hosted symbol for Host.response_stream_send!
/// Roc signature: U64, List(U8) => Try({}, [StreamDisconnected, StreamRefused])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg1.decref(roc_host);
pub extern fn hosted_response_stream_send(arg0: u64, arg1: RocListWith(u8, false)) callconv(.c) HostResponse_stream_startResult;

/// Hosted symbol for Host.response_stream_flush!
/// Roc signature: U64 => Try({}, [StreamDisconnected, StreamRefused])
pub extern fn hosted_response_stream_flush(arg0: u64) callconv(.c) HostResponse_stream_startResult;

/// Hosted symbol for Host.response_stream_end!
/// Roc signature: U64 => Try({}, [StreamDisconnected, StreamRefused])
pub extern fn hosted_response_stream_end(arg0: u64) callconv(.c) HostResponse_stream_startResult;

/// Hosted symbol for Host.sqlite_open!
/// Roc signature: Str, Str, List({ columns : List(U8), name : Str, params : List(U8), rows_max : U32, sql : Str, writes : Bool }) => Try({}, Str)
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
///     arg1.decref(roc_host);
///     decrefListOf__AnonStruct_2d568438e96cd20c(arg2, roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_sqlite_open(arg0: RocStr, arg1: RocStr, arg2: RocList(__AnonStruct_2d568438e96cd20c)) callconv(.c) HostSqlite_openResult;

/// Hosted symbol for Host.sqlite_run!
/// Roc signature: U64, U32, Bool, List([Blob(List(U8)), Integer(I64), Null, Real(F64), Text(Str)]) => Try(List(List([Blob(List(U8)), Integer(I64), Null, Real(F64), Text(Str)])), { code : U8, message : Str })
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     decrefListOfBlobOrIntegerOrNullOrRealOrText(arg3, roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_sqlite_run(arg0: u64, arg1: u32, arg2: bool, arg3: RocList(BlobOrIntegerOrNullOrRealOrText)) callconv(.c) HostSqlite_runResult;

/// Hosted symbol for Host.sqlite_write_begin!
/// Roc signature: U64 => Try({}, { code : U8, message : Str })
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_sqlite_write_begin(arg0: u64) callconv(.c) HostSqlite_write_beginResult;

/// Hosted symbol for Host.sqlite_commit!
/// Roc signature: U64 => Try({}, { code : U8, message : Str })
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn hosted_sqlite_commit(arg0: u64) callconv(.c) HostSqlite_write_beginResult;


/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) *anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) *anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.

/// Entrypoint: init_for_host!
pub extern fn roc_init_for_host() callconv(.c) Init_for_hostResult;

/// Entrypoint: respond_for_host!
pub extern fn roc_respond_for_host(arg0: __AnonStruct_28781edfe447a702, arg1: RocBox) callconv(.c) __AnonStruct_a14cd3b7d5755441;

