# Generated by roux build from Page.rocstache. DO NOT EDIT.
# Its contract and walkers only: markup changes leave this file alone.
import pf.Rocstache

Page :: [].{

	## The menu page. Declared rather than inferred, because the prices are
	## numbers (an inferred contract's values are `Str`).
	Ctx : { items : List({ name : Str, price : U32 }), title : Str }

	## The page as parts, from the templates' bytecode (`Rocstache.load!`):
	## `Rocstache.bytes!` writes them out.
	render : Rocstache.Templates, Ctx -> Rocstache.Html
	render = |code, ctx| walk(code, ctx, List.with_capacity(64))

	## The page's parts after `parts`: how a template calling this one
	## renders it.
	walk : Rocstache.Templates, Ctx, Rocstache.Html -> Rocstache.Html
	walk = |code, ctx, parts| {
		start = List.get(code, 1) ?? 0
		end = List.get(code, 2) ?? 0
		w0(ctx, code, start, end, parts)
	}
}

w0 : Page.Ctx, Rocstache.Templates, U64, U64, Rocstache.Html -> Rocstache.Html
w0 = |s0, code, start, end, parts| {
	var $parts = parts
	var $pc = start
	while $pc < end {
		w = List.get(code, $pc) ?? 0
		op = w % 16
		if op == 0 {
			$parts = $parts.append(Text(w // 1048576))
			$pc = $pc + 1
		} else if op == 1 {
			run = List.get(code, $pc + 1) ?? 0
			$parts = match (w // 16) % 65536 {
				1 => $parts.append(Value(run, s0.title))
				_ => $parts
			}
			$pc = $pc + 2
		} else if op == 3 {
			body = $pc + 1
			stop = body + w // 1048576
			$parts = match (w // 16) % 65536 {
				0 => {
					var $p = $parts
					for e in s0.items {
						$p = w3(e, s0, code, body, stop, $p)
					}
					$p
				}
				_ => $parts
			}
			$pc = stop
		} else if op == 4 {
			skip = match (w // 16) % 65536 {
				0 => !(s0.items.is_empty())
				_ => Bool.False
			}
			$pc = if skip $pc + 1 + w // 1048576 else $pc + 1
		} else if op == 6 {
			run = List.get(code, $pc + 1) ?? 0
			$parts = match (w // 16) % 65536 {
				0 => $parts.append(Unsigned(run, s0.items.len()))
				_ => $parts
			}
			$pc = $pc + 2
		} else if op == 7 {
			run = List.get(code, $pc + 1) ?? 0
			one = List.get(code, $pc + 2) ?? 0
			many = List.get(code, $pc + 3) ?? 0
			$parts = match (w // 16) % 65536 {
				0 => {
					n = s0.items.len()
					$parts.append(Unsigned(run, n)).append(Text(if n == 1 one else many))
				}
				_ => $parts
			}
			$pc = $pc + 4
		} else {
			$pc = $pc + 1
		}
	}
	$parts
}

w3 : { name : Str, price : U32 }, Page.Ctx, Rocstache.Templates, U64, U64, Rocstache.Html -> Rocstache.Html
w3 = |s0, s1, code, start, end, parts| {
	var $parts = parts
	var $pc = start
	while $pc < end {
		w = List.get(code, $pc) ?? 0
		op = w % 16
		if op == 0 {
			$parts = $parts.append(Text(w // 1048576))
			$pc = $pc + 1
		} else if op == 1 {
			run = List.get(code, $pc + 1) ?? 0
			$parts = match (w // 16) % 65536 {
				0 => $parts.append(Value(run, s0.name))
				4097 => $parts.append(Value(run, s1.title))
				_ => $parts
			}
			$pc = $pc + 2
		} else if op == 2 {
			run = List.get(code, $pc + 1) ?? 0
			$parts = match (w // 16) % 65536 {
				1 => $parts.append(Unsigned(run, s0.price.to_u64()))
				_ => $parts
			}
			$pc = $pc + 2
		} else if op == 3 {
			body = $pc + 1
			stop = body + w // 1048576
			$parts = match (w // 16) % 65536 {
				4096 => {
					var $p = $parts
					for e in s1.items {
						$p = w3(e, s1, code, body, stop, $p)
					}
					$p
				}
				_ => $parts
			}
			$pc = stop
		} else if op == 4 {
			skip = match (w // 16) % 65536 {
				4096 => !(s1.items.is_empty())
				_ => Bool.False
			}
			$pc = if skip $pc + 1 + w // 1048576 else $pc + 1
		} else if op == 6 {
			run = List.get(code, $pc + 1) ?? 0
			$parts = match (w // 16) % 65536 {
				4096 => $parts.append(Unsigned(run, s1.items.len()))
				_ => $parts
			}
			$pc = $pc + 2
		} else if op == 7 {
			run = List.get(code, $pc + 1) ?? 0
			one = List.get(code, $pc + 2) ?? 0
			many = List.get(code, $pc + 3) ?? 0
			$parts = match (w // 16) % 65536 {
				1 => {
					n = s0.price.to_u64()
					$parts.append(Unsigned(run, n)).append(Text(if n == 1 one else many))
				}
				4096 => {
					n = s1.items.len()
					$parts.append(Unsigned(run, n)).append(Text(if n == 1 one else many))
				}
				_ => $parts
			}
			$pc = $pc + 4
		} else {
			$pc = $pc + 1
		}
	}
	$parts
}
