# Generated by roux build from Page.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache

Page :: [].{

	## The menu page. Declared rather than inferred, because the prices are
	## numbers (an inferred contract's values are `Str`).
	Ctx : { items : List({ name : Str, price : U32 }), title : Str }

	## The page, rendered by the host from the template's bytecode.
	render! : Ctx => Rocstache.Html
	render! = |ctx| Rocstache.render!(0, Box.box(ctx))
}
