# Generated by roux build from Page.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

Page :: [].{

	## The menu page. Declared rather than inferred, because the prices are
	## numbers (an inferred contract's values are `Str`).
	Ctx : { items : List({ name : Str, price : U32 }), title : Str }

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0xd2eb6728096fdba3, Box.box(ctx))
}
