# Generated by roux build from the app's templates. DO NOT EDIT.
# The contracts spelled out, so each template's module can import this one.

Templates :: [].{
	## Every template of the app, a tag each, holding what it reads.
	Template : [
		Page({ items : List({ name : Str, price : U32 }), title : Str }),
	]

	## The layouts these templates were compiled for: the host renders
	## only a value made for its program's.
	layouts : U64
	layouts = 0xf1c8d176c052f990
}
