app [Context, program] { pf: platform "../../platform/main.roc" }

import pf.Server
import pf.Sqlite
import pf.Url
import db/Database
import db/Dishes
import db/Reviews

## A database, and its negative space. `db/*.roc` is generated by roux-db
## from `db/schema.sql` and the query files (`zig build examples`):
##
## - `GET /`: every dish with its average stars (NULL for none: a LEFT JOIN)
## - `GET /dishes/ID`: one dish, or 404
## - `POST /dishes?name=N&price_kr=P[&note=T]`: a new dish; a name taken, or
##   a price not over 0, is a constraint: 400
## - `POST /dishes/ID/rename?name=N`
## - `POST /reviews?dish_id=D&stars=S`: a dish that is not there, or stars
##   outside 1 to 5, is a constraint: 400
## - `GET /reviews/count`
## - `GET /write-on-get`: `Sqlite.write!` for a GET is refused: 500
## - `POST /forget`: a write never committed: rolled back, and 500
## - `POST /body-during-write`: the body read while holding the writer is
##   `BodyDuringWrite`, said in the answer
Context : { db : Sqlite.Db }

program = { init!, respond! }

init! : () => Try({ config : Server.Config, context : Context }, [Exit(I64), DbErr(Sqlite.Err)])
init! = || {
	db = Sqlite.open!(Database.at("dishes.db"))?
	Ok({ config: { port: 8080, static_dir: "" }, context: { db: db } })
}

Err : [NotFound, BadRequest(Str), DbErr(Sqlite.Err)]

respond! : Server.Request, Context => Try(Server.Response, Err)
respond! = |request, { db }| {
	path =
		match request.target.split_first("?") {
			Ok({ before, .. }) => before
			Err(_) => request.target
		}
	match (request.method, path.split_on("/")) {
		("GET", ["", ""]) => menu!(db, request)
		("GET", ["", "dishes", id]) => dish!(db, request, id)
		("POST", ["", "dishes"]) => add_dish!(db, request)
		("POST", ["", "dishes", id, "rename"]) => rename!(db, request, id)
		("POST", ["", "reviews"]) => review!(db, request)
		("GET", ["", "reviews", "count"]) => {
			{ reviews } = Reviews.count!(Sqlite.read(db, request))?
			Ok(Server.text("${reviews.to_str()} reviews\n"))
		}
		("GET", ["", "write-on-get"]) => {
			_ = Sqlite.write!(db, request)?
			Ok(Server.text("written\n"))
		}
		("POST", ["", "forget"]) => {
			tx = Sqlite.write!(db, request)?
			_ = Dishes.add!(tx, { name: "Forgotten", price_kr: 1, note: Null })?
			Ok(Server.text("returned without Sqlite.commit!\n"))
		}
		("POST", ["", "body-during-write"]) => {
			tx = Sqlite.write!(db, request)?
			said =
				match Server.read_body!(request, 1024) {
					Ok(_) => "read"
					Err(BodyErr(err)) => Str.inspect(err)
				}
			Sqlite.commit!(tx)?
			Ok(Server.text("${said}\n"))
		}
		_ => Err(NotFound)
	}
}

menu! : Sqlite.Db, Server.Request => Try(Server.Response, Err)
menu! = |db, request| {
	dishes = Dishes.with_stars!(Sqlite.read(db, request))?
	lines = dishes.map(
		|{ name, average, best_stars }| {
			stars =
				match (average, best_stars) {
					(NotNull(mean), NotNull(best)) => "${mean.to_str()} stars, best ${best.to_str()}"
					_ => "no reviews"
				}
			"${name}: ${stars}"
		},
	)
	Ok(Server.text("${Str.join_with(lines, "\n")}\n"))
}

dish! : Sqlite.Db, Server.Request, Str => Try(Server.Response, Err)
dish! = |db, request, id_text| {
	id = parse_i64(id_text)?
	{ name, price_kr, note, .. } = Dishes.by_id!(Sqlite.read(db, request), { id: id })?
	about =
		match note {
			NotNull(text) => " (${text})"
			Null => ""
		}
	Ok(Server.text("${name}: ${price_kr.to_str()} kr${about}\n"))
}

add_dish! : Sqlite.Db, Server.Request => Try(Server.Response, Err)
add_dish! = |db, request| {
	name = query(request, "name")?
	price_kr = parse_i64(query(request, "price_kr")?)?
	note =
		match Url.query_value(request.target, "note") {
			Ok(text) => NotNull(text)
			Err(_) => Null
		}
	tx = Sqlite.write!(db, request)?
	{ id } = Dishes.add!(tx, { name, price_kr, note }) ? constraint_as_bad_request
	Sqlite.commit!(tx)?
	Ok({ status: 201, headers: [], body: Str.to_utf8("dish ${id.to_str()}\n") })
}

rename! : Sqlite.Db, Server.Request, Str => Try(Server.Response, Err)
rename! = |db, request, id_text| {
	id = parse_i64(id_text)?
	name = query(request, "name")?
	tx = Sqlite.write!(db, request)?
	Dishes.rename!(tx, { id, name }) ? constraint_as_bad_request
	Sqlite.commit!(tx)?
	Ok(Server.text("renamed\n"))
}

review! : Sqlite.Db, Server.Request => Try(Server.Response, Err)
review! = |db, request| {
	dish_id = parse_i64(query(request, "dish_id")?)?
	stars = parse_i64(query(request, "stars")?)?
	tx = Sqlite.write!(db, request)?
	Reviews.add!(tx, { dish_id, stars }) ? constraint_as_bad_request
	Sqlite.commit!(tx)?
	Ok({ status: 201, headers: [], body: Str.to_utf8("reviewed\n") })
}

## A constraint the request broke is the client's: 400, saying which.
constraint_as_bad_request : [DbErr(Sqlite.Err), NotFound] -> Err
constraint_as_bad_request = |err|
	match err {
		DbErr(Constraint(message)) => BadRequest(message)
		DbErr(other) => DbErr(other)
		NotFound => NotFound
	}

query : Server.Request, Str -> Try(Str, [BadRequest(Str)])
query = |request, key|
	match Url.query_value(request.target, key) {
		Ok(value) => Ok(value)
		Err(_) => Err(BadRequest("?${key}= is missing or not UTF-8"))
	}

parse_i64 : Str -> Try(I64, [BadRequest(Str)])
parse_i64 = |text|
	match I64.from_str(text) {
		Ok(n) => Ok(n)
		Err(_) => Err(BadRequest("not a number: ${text}"))
	}
