# Generated by roux-db from schema.sql, Dishes.sql, Tags.sql. DO NOT EDIT.
import pf.Sqlite

## The database: `schema.sql`, and every statement the queries beside it
## run, numbered as they call them. In `init!`:
## `Sqlite.open!(Database.at(path))`.
Database :: [].{
	at : Str -> Sqlite.Database
	at = |path| { path, schema, statements }
}

schema : Str
schema = "-- The golden test's database (tests.zig): `roux-db gen` on this\n-- directory writes the expected Roc beside it.\nCREATE TABLE dish (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  price_kr INTEGER NOT NULL,\n  note TEXT,\n  vegetarian INTEGER NOT NULL DEFAULT 0\n) STRICT;\n\nCREATE INDEX dish_by_name ON dish (name);\n\nCREATE TABLE tag (\n  dish_id INTEGER NOT NULL REFERENCES dish (id),\n  label TEXT NOT NULL,\n  PRIMARY KEY (dish_id, label)\n) STRICT, WITHOUT ROWID;\n"

statements : List(Sqlite.Statement)
statements = [
	# 0: Dishes.sql:1
	{ name: "Dishes.by_id", sql: "SELECT id, name, price_kr, note FROM dish WHERE id = :id;", writes: Bool.False, rows_max: 1, params: [1], columns: [1, 3, 1, 19] },
	# 1: Dishes.sql:6
	{ name: "Dishes.cheap", sql: "SELECT name, count(*) OVER () AS n FROM dish WHERE price_kr < :below ORDER BY name;", writes: Bool.False, rows_max: 100, params: [1], columns: [3, 1] },
	# 2: Dishes.sql:11
	{ name: "Dishes.rename", sql: "UPDATE dish SET name = :name WHERE id = :id;", writes: Bool.True, rows_max: 0, params: [3, 1], columns: [] },
	# 3: Dishes.sql:16
	{ name: "Dishes.add", sql: "INSERT INTO dish (name, price_kr, note, vegetarian)\nVALUES (:name, :price_kr, :note, :vegetarian)\nRETURNING id;", writes: Bool.True, rows_max: 1, params: [3, 1, 19, 5], columns: [1] },
	# 4: Dishes.sql:25
	{ name: "Dishes.flags", sql: "SELECT vegetarian, note FROM dish;", writes: Bool.False, rows_max: 1000, params: [], columns: [5, 3] },
	# 5: Tags.sql:1
	{ name: "Tags.of_dish", sql: "SELECT dish_id, label FROM tag WHERE dish_id = :dish_id ORDER BY label;", writes: Bool.False, rows_max: 50, params: [1], columns: [1, 3] },
]
