# Generated by roux-db from Dishes.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Dishes.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Dishes :: [].{

	## A row of `by_id`.
	ById : { id : I64, name : Str, price_kr : I64, note : Sqlite.Nullable(Str) }

	## `by_id`, Dishes.sql:1: one row, or `NotFound`.
	by_id! : Sqlite.Read, { id : I64 } => Try(ById, [NotFound, DbErr(Sqlite.Err)])
	by_id! = |db, params| {
		rows = Sqlite.run_read!(db, 0, [Sqlite.Param.i64(params.id)])? # Dishes.sql:3
		match rows {
			[] => Err(NotFound)
			[[c0, c1, c2, c3]] => Ok({ id: Sqlite.Cell.i64(c0), name: Sqlite.Cell.str(c1), price_kr: Sqlite.Cell.i64(c2), note: Sqlite.Cell.nullable_str(c3) })
			_ => crash "roux-db: Dishes.by_id: rows the host should have refused"
		}
	}

	## A row of `cheap`.
	Cheap : { name : Str, n : I64 }

	## `cheap`, Dishes.sql:6: the rows, at most `:many`'s bound (more is `TooManyRows`).
	cheap! : Sqlite.Read, { below : I64 } => Try(List(Cheap), [DbErr(Sqlite.Err)])
	cheap! = |db, params| {
		rows = Sqlite.run_read!(db, 1, [Sqlite.Param.i64(params.below)])? # Dishes.sql:9
		Ok(
			rows.map(
				|row| match row {
					[c0, c1] => { name: Sqlite.Cell.str(c0), n: Sqlite.Cell.i64(c1) }
					_ => crash "roux-db: Dishes.cheap: a row the host should have refused"
				},
			),
		)
	}

	## `rename`, Dishes.sql:11: no rows.
	rename! : Sqlite.Write, { name : Str, id : I64 } => Try({}, [DbErr(Sqlite.Err)])
	rename! = |db, params| {
		_ = Sqlite.run_write!(db, 2, [Sqlite.Param.str(params.name), Sqlite.Param.i64(params.id)])? # Dishes.sql:14
		Ok({})
	}

	## A row of `add`.
	Add : { id : I64 }

	## `add`, Dishes.sql:16: one row, or `NotFound`.
	add! : Sqlite.Write, { name : Str, price_kr : I64, note : Sqlite.Nullable(Str), vegetarian : Bool } => Try(Add, [NotFound, DbErr(Sqlite.Err)])
	add! = |db, params| {
		rows = Sqlite.run_write!(db, 3, [Sqlite.Param.str(params.name), Sqlite.Param.i64(params.price_kr), Sqlite.Param.nullable_str(params.note), Sqlite.Param.bool(params.vegetarian)])? # Dishes.sql:21
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ id: Sqlite.Cell.i64(c0) })
			_ => crash "roux-db: Dishes.add: rows the host should have refused"
		}
	}

	## A row of `flags`.
	Flags : { vegetarian : Bool, note : Str }

	## `flags`, Dishes.sql:25: the rows, at most `:many`'s bound (more is `TooManyRows`).
	flags! : Sqlite.Read => Try(List(Flags), [DbErr(Sqlite.Err)])
	flags! = |db| {
		rows = Sqlite.run_read!(db, 4, [])? # Dishes.sql:29
		Ok(
			rows.map(
				|row| match row {
					[c0, c1] => { vegetarian: Sqlite.Cell.bool(c0), note: Sqlite.Cell.str(c1) }
					_ => crash "roux-db: Dishes.flags: a row the host should have refused"
				},
			),
		)
	}
}
