# Generated by roux-db from Tags.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Tags.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Tags :: [].{

	## A row of `of_dish`.
	OfDish : { dish_id : I64, label : Str }

	## `of_dish`, Tags.sql:1: the rows, at most `:many`'s bound (more is `TooManyRows`).
	of_dish! : Sqlite.Read, { dish_id : I64 } => Try(List(OfDish), [DbErr(Sqlite.Err)])
	of_dish! = |db, params| {
		rows = Sqlite.run_read!(db, 5, [Sqlite.Param.i64(params.dish_id)])? # Tags.sql:3
		Ok(
			rows.map(
				|row| match row {
					[c0, c1] => { dish_id: Sqlite.Cell.i64(c0), label: Sqlite.Cell.str(c1) }
					_ => crash "roux-db: Tags.of_dish: a row the host should have refused"
				},
			),
		)
	}
}
