# Generated by roux build from Notes.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache
import Templates

Notes :: [].{

	## What `Notes.rocstache` reads, inferred from its tags.
	Ctx : { notes : Str }

	## The template's value: what a response sends, rendered by the
	## host from the template's bytecode as it is sent.
	template : Ctx -> Rocstache.Template(Templates.Template)
	template = |ctx| { layouts: Templates.layouts, template: Notes(ctx) }
}
