# Generated by roux build from Notes.rocstache. DO NOT EDIT.
# The template's contract only: markup changes leave this file alone.
import pf.Rocstache

Notes :: [].{

	## What `Notes.rocstache` reads, inferred from its tags.
	Ctx : { notes : Str }

	## The page: the template as compiled into the app, rendered by the host.
	render! : Ctx => Str
	render! = |ctx| Rocstache.compiled_render!(0xd0ee6258dcd02194, Box.box(ctx))
}
