# Generated by roux build from Notes.rocstache. DO NOT EDIT.
# Its contract only: markup changes leave this file alone.
import pf.Rocstache

Notes :: [].{

	## What `Notes.rocstache` reads, inferred from its tags.
	Ctx : { notes : Str }

	## The page, rendered by the host from the template's bytecode.
	render! : Ctx => Rocstache.Html
	render! = |ctx| Rocstache.render!(0, Box.box(ctx))
}
