# Generated by roux-db from schema.sql, Dishes.sql, Reviews.sql. DO NOT EDIT.
import pf.Sqlite

## The database: `schema.sql`, and every statement the queries beside it
## run, numbered as they call them. In `init!`:
## `Sqlite.open!(Database.at(path), settings)`.
Database :: [].{
	at : Str -> Sqlite.Database
	at = |path| { path, schema, statements }
}

schema : Str
schema = "-- The example's database: dishes and their reviews. STRICT, as roux-db\n-- requires: a column's declared type is what it holds.\nCREATE TABLE dish (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL UNIQUE,\n  price_kr INTEGER NOT NULL CHECK (price_kr > 0),\n  note TEXT\n) STRICT;\n\nCREATE TABLE review (\n  id INTEGER PRIMARY KEY,\n  dish_id INTEGER NOT NULL REFERENCES dish (id),\n  stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5)\n) STRICT;\n\nCREATE INDEX review_by_dish ON review (dish_id);\n"

statements : List(Sqlite.Statement)
statements = [
	# 0: Dishes.sql:1
	{ name: "Dishes.all", sql: "SELECT id, name, price_kr, note FROM dish ORDER BY name;", writes: Bool.False, rows_max: 200, params: [], columns: [1, 3, 1, 19] },
	# 1: Dishes.sql:4
	{ name: "Dishes.by_id", sql: "SELECT id, name, price_kr, note FROM dish WHERE id = :id;", writes: Bool.False, rows_max: 1, params: [1], columns: [1, 3, 1, 19] },
	# 2: Dishes.sql:8
	{ name: "Dishes.add", sql: "INSERT INTO dish (name, price_kr, note) VALUES (:name, :price_kr, :note)\nRETURNING id;", writes: Bool.True, rows_max: 1, params: [3, 1, 19], columns: [1] },
	# 3: Dishes.sql:15
	{ name: "Dishes.rename", sql: "UPDATE dish SET name = :name WHERE id = :id;", writes: Bool.True, rows_max: 0, params: [3, 1], columns: [] },
	# 4: Dishes.sql:22
	{ name: "Dishes.with_stars", sql: "SELECT d.name, avg(r.stars) AS average, max(r.stars) AS best_stars\nFROM dish d LEFT JOIN review r ON r.dish_id = d.id\nGROUP BY d.id ORDER BY d.name;", writes: Bool.False, rows_max: 200, params: [], columns: [3, 18, 17] },
	# 5: Reviews.sql:1
	{ name: "Reviews.add", sql: "INSERT INTO review (dish_id, stars) VALUES (:dish_id, :stars);", writes: Bool.True, rows_max: 0, params: [1, 1], columns: [] },
	# 6: Reviews.sql:6
	{ name: "Reviews.count", sql: "SELECT count(*) AS reviews FROM review;", writes: Bool.False, rows_max: 1, params: [], columns: [1] },
]
