# Generated by roux-db from Dishes.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Dishes.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Dishes :: [].{

	## A row of `all`.
	All : { id : I64, name : Str, price_kr : I64, note : Sqlite.Nullable(Str) }

	## `all`, Dishes.sql:1: the rows, at most `:many`'s bound (more is `TooManyRows`).
	all! : Sqlite.Read => Try(List(All), [DbErr(Sqlite.Err)])
	all! = |db| {
		rows = Sqlite.run_read!(db, 0, [])? # Dishes.sql:2
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2, c3] => { id: Sqlite.Cell.i64(c0), name: Sqlite.Cell.str(c1), price_kr: Sqlite.Cell.i64(c2), note: Sqlite.Cell.nullable_str(c3) }
					_ => crash "roux-db: Dishes.all: a row the host should have refused"
				},
			),
		)
	}

	## A row of `by_id`.
	ById : { id : I64, name : Str, price_kr : I64, note : Sqlite.Nullable(Str) }

	## `by_id`, Dishes.sql:4: one row, or `NotFound`.
	by_id! : Sqlite.Read, { id : I64 } => Try(ById, [NotFound, DbErr(Sqlite.Err)])
	by_id! = |db, params| {
		rows = Sqlite.run_read!(db, 1, [Sqlite.Param.i64(params.id)])? # Dishes.sql:6
		match rows {
			[] => Err(NotFound)
			[[c0, c1, c2, c3]] => Ok({ id: Sqlite.Cell.i64(c0), name: Sqlite.Cell.str(c1), price_kr: Sqlite.Cell.i64(c2), note: Sqlite.Cell.nullable_str(c3) })
			_ => crash "roux-db: Dishes.by_id: rows the host should have refused"
		}
	}

	## A row of `add`.
	Add : { id : I64 }

	## `add`, Dishes.sql:8: one row, or `NotFound`.
	add! : Sqlite.Write, { name : Str, price_kr : I64, note : Sqlite.Nullable(Str) } => Try(Add, [NotFound, DbErr(Sqlite.Err)])
	add! = |db, params| {
		rows = Sqlite.run_write!(db, 2, [Sqlite.Param.str(params.name), Sqlite.Param.i64(params.price_kr), Sqlite.Param.nullable_str(params.note)])? # Dishes.sql:12
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ id: Sqlite.Cell.i64(c0) })
			_ => crash "roux-db: Dishes.add: rows the host should have refused"
		}
	}

	## `rename`, Dishes.sql:15: no rows.
	rename! : Sqlite.Write, { name : Str, id : I64 } => Try({}, [DbErr(Sqlite.Err)])
	rename! = |db, params| {
		_ = Sqlite.run_write!(db, 3, [Sqlite.Param.str(params.name), Sqlite.Param.i64(params.id)])? # Dishes.sql:18
		Ok({})
	}

	## A row of `with_stars`.
	WithStars : { name : Str, average : Sqlite.Nullable(F64), best_stars : Sqlite.Nullable(I64) }

	## `with_stars`, Dishes.sql:22: the rows, at most `:many`'s bound (more is `TooManyRows`).
	with_stars! : Sqlite.Read => Try(List(WithStars), [DbErr(Sqlite.Err)])
	with_stars! = |db| {
		rows = Sqlite.run_read!(db, 4, [])? # Dishes.sql:25
		Ok(
			rows.map(
				|row| match row {
					[c0, c1, c2] => { name: Sqlite.Cell.str(c0), average: Sqlite.Cell.nullable_f64(c1), best_stars: Sqlite.Cell.nullable_i64(c2) }
					_ => crash "roux-db: Dishes.with_stars: a row the host should have refused"
				},
			),
		)
	}
}
