# Generated by roux-db from Reviews.sql. DO NOT EDIT.
import pf.Sqlite

## The queries of `Reviews.sql`, typed by SQLite against `schema.sql`. Each runs a
## statement the host prepared at startup (`Database.roc`).
Reviews :: [].{

	## `add`, Reviews.sql:1: no rows.
	add! : Sqlite.Write, { dish_id : I64, stars : I64 } => Try({}, [DbErr(Sqlite.Err)])
	add! = |db, params| {
		_ = Sqlite.run_write!(db, 5, [Sqlite.Param.i64(params.dish_id), Sqlite.Param.i64(params.stars)])? # Reviews.sql:4
		Ok({})
	}

	## A row of `count`.
	Count : { reviews : I64 }

	## `count`, Reviews.sql:6: one row, or `NotFound`.
	count! : Sqlite.Read => Try(Count, [NotFound, DbErr(Sqlite.Err)])
	count! = |db| {
		rows = Sqlite.run_read!(db, 6, [])? # Reviews.sql:8
		match rows {
			[] => Err(NotFound)
			[[c0]] => Ok({ reviews: Sqlite.Cell.i64(c0) })
			_ => crash "roux-db: Reviews.count: rows the host should have refused"
		}
	}
}
